import type { AppContent } from "../app-types";

export const app: AppContent = {
  login: {
    title: "Đăng nhập",
    subtitle: "Nhận liên kết đăng nhập qua email, không cần mật khẩu.",
    email: "Email",
    sendLink: "Gửi liên kết đăng nhập",
    sending: "Đang gửi…",
    linkSent: "Đã gửi! Kiểm tra hộp thư và nhấn vào liên kết để đăng nhập.",
    or: "hoặc",
    google: "Tiếp tục với Google",
    errors: {
      invalid_email: "Email không hợp lệ.",
      rate_limited: "Bạn yêu cầu quá nhiều lần. Vui lòng thử lại sau ít phút.",
      error: "Không gửi được liên kết. Vui lòng thử lại.",
      link: "Liên kết đăng nhập không hợp lệ hoặc đã hết hạn. Hãy yêu cầu liên kết mới.",
    },
  },
  dashboard: {
    nav: { overview: "Tổng quan", account: "Tài khoản" },
    signOut: "Đăng xuất",
    welcome: "Xin chào",
    overviewText: "Đây là dashboard mẫu. Phần sản phẩm nằm trong mục Ghi chú.",
  },
  account: {
    title: "Tài khoản",
    profile: "Thông tin",
    exportTitle: "Xuất dữ liệu",
    exportText: "Tải toàn bộ dữ liệu của bạn dưới dạng JSON.",
    exportButton: "Tải xuống",
    deleteTitle: "Xoá tài khoản",
    deleteText: "Xoá vĩnh viễn tài khoản và toàn bộ dữ liệu. Không thể hoàn tác.",
    deleteConfirmLabel: "Nhập email của bạn để xác nhận",
    deleteButton: "Xoá tài khoản",
  },
  billing: {
    title: "Gói dịch vụ",
    currentPlan: "Gói hiện tại",
    activeUntil: "Hiệu lực đến",
    renewsAutomatically: "Tự động gia hạn qua Polar",
    upgradeTitle: "Nâng cấp hoặc gia hạn Pro",
    monthly: "1 tháng",
    yearly: "1 năm",
    payInternational: "Thẻ quốc tế (Polar, tự gia hạn)",
    payVietnam: "VNPay (thanh toán một lần)",
    vietnamNote: "Thanh toán VNPay cộng thêm thời gian vào gói hiện tại, không tự trừ tiền.",
    manage: "Quản lý gói trên Polar",
    pricingTitle: "Bảng giá",
    pricingSubtitle: "Bắt đầu miễn phí, nâng cấp khi cần.",
    perMonth: "/ tháng",
    perYear: "/ năm",
    choosePlan: "Chọn gói",
    returnPaid: "Thanh toán thành công. Gói Pro đã được kích hoạt.",
    returnPending: "Đang chờ VNPay xác nhận thanh toán. Vui lòng tải lại sau ít phút.",
    returnFailed: "Thanh toán không thành công. Bạn chưa bị trừ tiền cho gói này.",
    returnInvalid: "Không xác minh được kết quả thanh toán.",
    backToBilling: "Về trang gói dịch vụ",
    checkoutSuccess: "Cảm ơn bạn! Gói sẽ được kích hoạt trong giây lát.",
    error: "Không tạo được thanh toán. Vui lòng thử lại.",
  },
  legal: {
    terms: "Điều khoản sử dụng",
    privacy: "Chính sách quyền riêng tư",
    lastUpdated: "Cập nhật lần cuối",
    templateNotice: "Đây là mẫu. Hãy thay bằng nội dung pháp lý phù hợp với doanh nghiệp của bạn.",
  },
};
