import type { AppContent } from "../app-types";

export const app: AppContent = {
  login: {
    title: "Đăng nhập",
    subtitle: "Nhận liên kết đăng nhập qua email, không cần mật khẩu.",
    email: "Email",
    sendLink: "Gửi liên kết đăng nhập",
    sending: "Đang gửi…",
    linkSent: "Đã gửi! Kiểm tra hộp thư và nhấn vào liên kết để đăng nhập.",
    or: "hoặc",
    google: "Tiếp tục với Google",
    errors: {
      invalid_email: "Email không hợp lệ.",
      rate_limited: "Bạn yêu cầu quá nhiều lần. Vui lòng thử lại sau ít phút.",
      error: "Không gửi được liên kết. Vui lòng thử lại.",
      link: "Liên kết đăng nhập không hợp lệ hoặc đã hết hạn. Hãy yêu cầu liên kết mới.",
    },
  },
  dashboard: {
    nav: { overview: "Tổng quan", account: "Tài khoản", admin: "Quản trị" },
    shell: { menu: "Menu", toggle: "Ẩn/hiện menu", skip: "Bỏ qua, đến nội dung chính", breadcrumb: "Đường dẫn" },
    signOut: "Đăng xuất",
    welcome: "Xin chào",
    overviewText: "Đây là dashboard mẫu. Phần sản phẩm nằm trong mục Ghi chú.",
  },
  account: {
    title: "Tài khoản",
    profile: "Thông tin",
    exportTitle: "Xuất dữ liệu",
    exportText: "Tải toàn bộ dữ liệu của bạn dưới dạng JSON.",
    exportButton: "Tải xuống",
    deleteTitle: "Xoá tài khoản",
    deleteText: "Xoá vĩnh viễn tài khoản và toàn bộ dữ liệu. Không thể hoàn tác.",
    deleteConfirmLabel: "Nhập email của bạn để xác nhận",
    deleteButton: "Xoá tài khoản",
  },
  billing: {
    title: "Gói dịch vụ",
    currentPlan: "Gói hiện tại",
    activeUntil: "Hiệu lực đến",
    renewsAutomatically: "Tự động gia hạn qua Polar",
    upgradeTitle: "Nâng cấp hoặc gia hạn Pro",
    monthly: "1 tháng",
    yearly: "1 năm",
    payInternational: "Thẻ quốc tế (Polar, tự gia hạn)",
    payVietnam: "VNPay (thanh toán một lần)",
    vietnamNote: "Thanh toán VNPay cộng thêm thời gian vào gói hiện tại, không tự trừ tiền.",
    manage: "Quản lý gói trên Polar",
    pricingTitle: "Bảng giá",
    pricingSubtitle: "Bắt đầu miễn phí, nâng cấp khi cần.",
    perMonth: "/ tháng",
    perYear: "/ năm",
    choosePlan: "Chọn gói",
    returnPaid: "Thanh toán thành công. Gói Pro đã được kích hoạt.",
    returnPending: "Đang chờ VNPay xác nhận thanh toán. Vui lòng tải lại sau ít phút.",
    returnFailed: "Thanh toán không thành công. Bạn chưa bị trừ tiền cho gói này.",
    returnInvalid: "Không xác minh được kết quả thanh toán.",
    backToBilling: "Về trang gói dịch vụ",
    checkoutSuccess: "Cảm ơn bạn! Gói sẽ được kích hoạt trong giây lát.",
    error: "Không tạo được thanh toán. Vui lòng thử lại.",
    rateLimited: "Bạn thử quá nhiều lần. Vui lòng đợi vài phút rồi thử lại.",
  },
  legal: {
    terms: "Điều khoản sử dụng",
    privacy: "Chính sách quyền riêng tư",
    lastUpdated: "Cập nhật lần cuối",
    templateNotice: "Chính sách đang được hoàn thiện và có thể thay đổi. Nếu cần giải đáp, vui lòng liên hệ hotline hoặc Zalo.",
  },
  files: {
    title: "Tệp của tôi",
    usage: "Đã dùng",
    upload: "Tải tệp lên",
    uploading: "Đang tải lên…",
    allowed: "Ảnh, PDF, văn bản. Tối đa",
    empty: "Chưa có tệp nào.",
    download: "Tải xuống",
    delete: "Xoá",
    errors: {
      type: "Loại tệp này không được hỗ trợ.",
      size: "Tệp quá lớn.",
      quota: "Bạn đã hết dung lượng lưu trữ. Nâng cấp gói để có thêm.",
      failed: "Tải lên thất bại. Vui lòng thử lại.",
    },
  },
  consent: {
    text: "Chúng tôi dùng thống kê nội bộ (không chia sẻ với bên thứ ba) để cải thiện trang. Bạn có đồng ý không?",
    accept: "Đồng ý",
    decline: "Từ chối",
    privacyLink: "Chính sách bảo mật",
  },
  admin: {
    title: "Quản trị",
    backToApp: "Về dashboard",
    nav: { overview: "Tổng quan", users: "Người dùng", jobs: "Job nền", billing: "Thanh toán", audit: "Nhật ký", media: "Thư viện ảnh", content: "Duyệt nội dung" },
    overview: {
      newUsers: "Người dùng mới",
      proUsers: "Đang dùng Pro",
      totalUsers: "Tổng người dùng",
      views: "Lượt xem",
      visitors: "Khách (đã đồng ý)",
      topPages: "Trang xem nhiều",
      topReferrers: "Nguồn truy cập",
      events: "Sự kiện",
      storage: "Lưu trữ",
      noData: "Chưa có dữ liệu.",
      last30Days: "30 ngày qua",
    },
    users: {
      search: "Tìm theo email",
      email: "Email",
      role: "Vai trò",
      status: "Trạng thái",
      createdAt: "Ngày tạo",
      plan: "Gói",
      activeUntil: "Hiệu lực đến",
      orders: "Đơn hàng",
      subscriptions: "Subscription",
      files: "Tệp",
      disable: "Khoá tài khoản",
      enable: "Mở khoá",
      makeAdmin: "Cấp quyền admin",
      makeUser: "Bỏ quyền admin",
      previous: "Trước",
      next: "Sau",
      selfNote: "Bạn không thể khoá hoặc bỏ quyền admin của chính mình.",
      confirmDisable: "Người dùng sẽ bị đăng xuất và không đăng nhập lại được cho đến khi mở khoá.",
      confirmRole: "Quyền vào trang quản trị của người dùng này sẽ thay đổi.",
      changeRole: "Đổi vai trò",
      roles: { user: "Người dùng", editor: "Biên tập viên (sửa nội dung)", admin: "Quản trị viên" },
    },
    jobs: { title: "Job lỗi", name: "Tên", attempts: "Số lần", lastError: "Lỗi gần nhất", retry: "Chạy lại", empty: "Không có job lỗi." },
    billing: {
      subscriptions: "Subscription gần đây",
      orders: "Đơn VNPay gần đây",
      problemEvents: "Webhook lỗi",
      retry: "Xử lý lại",
      empty: "Không có.",
    },
    audit: { title: "Nhật ký quản trị", time: "Thời gian", actor: "Người thực hiện", action: "Hành động", target: "Đối tượng", empty: "Chưa có thao tác nào." },
    media: {
      title: "Thư viện ảnh",
      upload: "Tải ảnh lên",
      uploading: "Đang tải lên…",
      search: "Tìm theo tên tệp",
      empty: "Chưa có ảnh nào.",
      edit: "Sửa ảnh",
      back: "← Thư viện ảnh",
      alt: "Mô tả ảnh (alt)",
      altHint: "Mô tả ngắn nội dung ảnh cho người khiếm thị và Google, ví dụ: \"Du thuyền trên vịnh Hạ Long lúc hoàng hôn\".",
      focal: "Điểm lấy nét",
      focalHint: "Bấm vào chủ thể chính của ảnh: khi cắt ảnh theo khung khác nhau, điểm này luôn được giữ lại.",
      save: "Lưu",
      remove: "Xoá ảnh",
      removeAsk: "Xoá vĩnh viễn ảnh này khỏi thư viện?",
      size: "Kích thước",
      errors: {
        format: "Chỉ nhận ảnh JPG, PNG, WebP hoặc AVIF.",
        size: "Ảnh quá lớn.",
        failed: "Không tải được ảnh. Vui lòng thử lại.",
        inUse: "Ảnh đang được dùng trong nội dung đã công khai, không xoá được.",
      },
    },
    content: {
      title: "Duyệt nội dung",
      description: "Nội dung chờ duyệt, đã hẹn giờ và mới sửa.",
      empty: "Không có nội dung nào.",
      all: "Tất cả",
      type: "Loại",
      slug: "Đường dẫn",
      status: "Trạng thái",
      updated: "Cập nhật",
      statuses: { draft: "Nháp", pending: "Chờ duyệt", approved: "Đã duyệt, chờ đến giờ", published: "Đã công khai" },
      hidden: "Đang ẩn",
      live: "Đang hiển thị trên web",
      notLive: "Chưa hiển thị trên web",
      scheduledFor: "Công khai lúc",
      reviewNote: "Ghi chú của người duyệt",
      workflow: "Quy trình duyệt",
      submit: "Gửi duyệt",
      publishNow: "Duyệt và công khai ngay",
      schedule: "Duyệt và hẹn giờ",
      scheduleAt: "Thời điểm công khai",
      reject: "Trả lại để sửa",
      rejectNote: "Cần sửa gì?",
      hide: "Ẩn khỏi web",
      show: "Hiện lại trên web",
      preview: "Xem trước",
      previewing: "Đang xem trước bản nháp (khách không thấy).",
      exitPreview: "Thoát xem trước",
      history: "Lịch sử phiên bản",
      restore: "Khôi phục",
      restoreAsk: "Chép phiên bản này vào bản nháp? Bản nháp hiện tại sẽ bị thay thế.",
      events: { submitted: "Gửi duyệt", published: "Công khai" },
      conflict: "Nội dung vừa được người khác thay đổi. Tải lại trang để xem bản mới nhất.",
    },
    done: "Đã thực hiện.",
    failed: "Không thực hiện được.",
    confirmTitle: "Xác nhận thao tác",
    cancel: "Huỷ",
  },
  blog: {
    nav: "Blog",
    title: "Blog",
    subtitle: "Tin tức, kinh nghiệm và hướng dẫn.",
    readingTime: "{n} phút đọc",
    tagTitle: "Bài viết về",
    tags: "Chủ đề",
    empty: "Chưa có bài viết nào.",
    previous: "Trang trước",
    next: "Trang sau",
    allPosts: "Tất cả bài viết",
    updated: "Cập nhật",
    otherLanguage: "Đọc bằng tiếng Anh",
    rss: "RSS",
  },
};
