export interface AppContent {
  login: {
    title: string;
    subtitle: string;
    email: string;
    sendLink: string;
    sending: string;
    linkSent: string;
    or: string;
    google: string;
    errors: { invalid_email: string; rate_limited: string; error: string; link: string };
  };
  dashboard: {
    nav: { overview: string; account: string; admin: string };
    /** App shell (dashboard + admin): sidebar sheet title, toggle button, skip link, breadcrumb landmark. */
    shell: { menu: string; toggle: string; skip: string; breadcrumb: string };
    signOut: string;
    welcome: string;
    overviewText: string;
  };
  account: {
    title: string;
    profile: string;
    exportTitle: string;
    exportText: string;
    exportButton: string;
    deleteTitle: string;
    deleteText: string;
    deleteConfirmLabel: string;
    deleteButton: string;
  };
  legal: { terms: string; privacy: string; lastUpdated: string; templateNotice: string };
  billing: {
    title: string;
    currentPlan: string;
    activeUntil: string;
    renewsAutomatically: string;
    upgradeTitle: string;
    monthly: string;
    yearly: string;
    payInternational: string;
    payVietnam: string;
    vietnamNote: string;
    manage: string;
    pricingTitle: string;
    pricingSubtitle: string;
    perMonth: string;
    perYear: string;
    choosePlan: string;
    returnPaid: string;
    returnPending: string;
    returnFailed: string;
    returnInvalid: string;
    backToBilling: string;
    checkoutSuccess: string;
    error: string;
    rateLimited: string;
  };
  files: {
    title: string;
    usage: string;
    upload: string;
    uploading: string;
    allowed: string;
    empty: string;
    download: string;
    delete: string;
    errors: { type: string; size: string; quota: string; failed: string };
  };
  consent: { text: string; accept: string; decline: string; privacyLink: string };
  admin: {
    title: string;
    backToApp: string;
    nav: { overview: string; users: string; jobs: string; billing: string; audit: string; media: string; content: string };
    overview: {
      newUsers: string;
      proUsers: string;
      totalUsers: string;
      views: string;
      visitors: string;
      topPages: string;
      topReferrers: string;
      events: string;
      storage: string;
      noData: string;
      last30Days: string;
    };
    users: {
      search: string;
      email: string;
      role: string;
      status: string;
      createdAt: string;
      plan: string;
      activeUntil: string;
      orders: string;
      subscriptions: string;
      files: string;
      disable: string;
      enable: string;
      makeAdmin: string;
      makeUser: string;
      previous: string;
      next: string;
      selfNote: string;
      confirmDisable: string;
      confirmRole: string;
      changeRole: string;
      roles: { user: string; editor: string; admin: string };
    };
    jobs: { title: string; name: string; attempts: string; lastError: string; retry: string; empty: string };
    billing: { subscriptions: string; orders: string; problemEvents: string; retry: string; empty: string };
    audit: { title: string; time: string; actor: string; action: string; target: string; empty: string };
    media: {
      title: string;
      upload: string;
      uploading: string;
      search: string;
      empty: string;
      edit: string;
      back: string;
      alt: string;
      altHint: string;
      focal: string;
      focalHint: string;
      save: string;
      remove: string;
      removeAsk: string;
      size: string;
      errors: { format: string; size: string; failed: string; inUse: string };
    };
    content: {
      title: string;
      description: string;
      empty: string;
      all: string;
      type: string;
      slug: string;
      status: string;
      updated: string;
      statuses: { draft: string; pending: string; approved: string; published: string };
      hidden: string;
      live: string;
      notLive: string;
      scheduledFor: string;
      reviewNote: string;
      workflow: string;
      submit: string;
      publishNow: string;
      schedule: string;
      scheduleAt: string;
      reject: string;
      rejectNote: string;
      hide: string;
      show: string;
      preview: string;
      previewing: string;
      exitPreview: string;
      history: string;
      restore: string;
      restoreAsk: string;
      events: { submitted: string; published: string };
      conflict: string;
    };
    done: string;
    failed: string;
    confirmTitle: string;
    cancel: string;
  };
  blog: {
    nav: string;
    title: string;
    subtitle: string;
    /** "{n}" is replaced with the number of minutes. */
    readingTime: string;
    tagTitle: string;
    tags: string;
    empty: string;
    previous: string;
    next: string;
    allPosts: string;
    updated: string;
    otherLanguage: string;
    rss: string;
  };
}
