export interface AppContent {
  login: {
    title: string;
    subtitle: string;
    email: string;
    sendLink: string;
    sending: string;
    linkSent: string;
    or: string;
    google: string;
    errors: { invalid_email: string; rate_limited: string; error: string; link: string };
  };
  dashboard: {
    nav: { overview: string; account: string; admin: string };
    signOut: string;
    welcome: string;
    overviewText: string;
  };
  account: {
    title: string;
    profile: string;
    exportTitle: string;
    exportText: string;
    exportButton: string;
    deleteTitle: string;
    deleteText: string;
    deleteConfirmLabel: string;
    deleteButton: string;
  };
  legal: { terms: string; privacy: string; lastUpdated: string; templateNotice: string };
  billing: {
    title: string;
    currentPlan: string;
    activeUntil: string;
    renewsAutomatically: string;
    upgradeTitle: string;
    monthly: string;
    yearly: string;
    payInternational: string;
    payVietnam: string;
    vietnamNote: string;
    manage: string;
    pricingTitle: string;
    pricingSubtitle: string;
    perMonth: string;
    perYear: string;
    choosePlan: string;
    returnPaid: string;
    returnPending: string;
    returnFailed: string;
    returnInvalid: string;
    backToBilling: string;
    checkoutSuccess: string;
    error: string;
  };
  files: {
    title: string;
    usage: string;
    upload: string;
    uploading: string;
    allowed: string;
    empty: string;
    download: string;
    delete: string;
    errors: { type: string; size: string; quota: string; failed: string };
  };
  consent: { text: string; accept: string; decline: string; privacyLink: string };
  admin: {
    title: string;
    backToApp: string;
    nav: { overview: string; users: string; jobs: string; billing: string; audit: string };
    overview: {
      newUsers: string;
      proUsers: string;
      totalUsers: string;
      views: string;
      visitors: string;
      topPages: string;
      topReferrers: string;
      events: string;
      storage: string;
      noData: string;
      last30Days: string;
    };
    users: {
      search: string;
      email: string;
      role: string;
      status: string;
      createdAt: string;
      plan: string;
      activeUntil: string;
      orders: string;
      subscriptions: string;
      files: string;
      disable: string;
      enable: string;
      makeAdmin: string;
      makeUser: string;
      previous: string;
      next: string;
      selfNote: string;
    };
    jobs: { title: string; name: string; attempts: string; lastError: string; retry: string; empty: string };
    billing: { subscriptions: string; orders: string; problemEvents: string; retry: string; empty: string };
    audit: { title: string; time: string; actor: string; action: string; target: string; empty: string };
    done: string;
    failed: string;
  };
}
