import type { Locale } from "@/config/app";

/** Sign-in extras (passkey, email code, confirmation), the second-factor check and the account security page. */
const vi = {
  signIn: {
    passkey: "Đăng nhập bằng passkey",
    passkeyHint: "Face ID, vân tay hoặc mã PIN của thiết bị.",
    passkeyFailed: "Không đăng nhập được bằng passkey. Thử lại hoặc dùng email.",
    codeTitle: "Đã có mã 6 số trong email?",
    codeHint: "Dùng khi bạn đọc email trên thiết bị khác.",
    code: "Mã đăng nhập",
    useCode: "Đăng nhập bằng mã",
    codeWrong: "Mã không đúng hoặc đã hết hạn.",
    captcha: "Hãy xác nhận bạn không phải robot rồi gửi lại.",
    confirmTitle: "Xác nhận đăng nhập",
    confirmText: "Bấm nút dưới đây để đăng nhập trên thiết bị này. Liên kết dùng được một lần, trong 10 phút.",
    confirm: "Đăng nhập",
    confirmInvalid: "Liên kết không hợp lệ. Hãy yêu cầu liên kết mới.",
  },
  verify: {
    title: "Xác thực hai lớp",
    intro: "Khu quản trị cần thêm một bước xác thực cho phiên đăng nhập này.",
    fresh: "Thao tác này cần xác thực lại. Xác thực xong, hãy thực hiện lại thao tác.",
    passkey: "Xác thực bằng passkey",
    totp: "Mã từ ứng dụng Authenticator",
    totpSubmit: "Xác thực",
    backup: "Dùng mã khôi phục",
    backupCode: "Mã khôi phục",
    backupSubmit: "Dùng mã khôi phục",
    wrong: "Mã không đúng. Thử lại.",
    locked: "Sai quá nhiều lần. Tài khoản tạm khoá 15 phút.",
    passkeyFailed: "Không xác thực được bằng passkey.",
    signOut: "Đăng xuất",
  },
  page: {
    title: "Bảo mật tài khoản",
    enrollNotice: "Tài khoản nhân viên cần xác thực hai lớp. Hãy thêm passkey (khuyên dùng) hoặc ứng dụng Authenticator để vào khu quản trị.",
    freshNotice: "Thay đổi này cần xác thực lại trong 10 phút gần nhất.",
    passkeys: "Passkey",
    passkeysText: "Đăng nhập bằng Face ID, vân tay hoặc mã PIN của thiết bị. Chống trang giả mạo. Nên thêm trên cả điện thoại và máy tính.",
    addPasskey: "Thêm passkey cho thiết bị này",
    passkeyName: "Tên (ví dụ: iPhone của Lan)",
    noPasskeys: "Chưa có passkey.",
    remove: "Xoá",
    removeAsk: "Xoá passkey này?",
    lastFactor: "Đây là cách xác thực hai lớp cuối cùng: thêm cách khác trước khi xoá.",
    totp: "Ứng dụng Authenticator",
    totpText: "Google Authenticator, Microsoft Authenticator, 1Password… tạo mã 6 số mỗi 30 giây.",
    totpOn: "Đang bật",
    totpSetup: "Thiết lập ứng dụng Authenticator",
    totpScan: "Quét mã QR bằng ứng dụng, hoặc nhập khoá thủ công, rồi nhập mã 6 số để xác nhận.",
    totpKey: "Khoá thủ công",
    totpConfirm: "Xác nhận",
    totpDisable: "Tắt",
    totpDisableAsk: "Tắt ứng dụng Authenticator?",
    backupCodes: "Mã khôi phục",
    backupText: "Mỗi mã dùng được một lần, khi mất điện thoại. In ra hoặc lưu ở nơi an toàn. Mã chỉ hiện một lần.",
    newBackupCodes: "Tạo bộ mã mới (bộ cũ hết hiệu lực)",
    devices: "Thiết bị đang đăng nhập",
    thisDevice: "Thiết bị này",
    signOutDevice: "Đăng xuất",
    signOutOthers: "Đăng xuất tất cả thiết bị khác",
    since: "Từ",
    activity: "Hoạt động gần đây",
    events: {
      sign_in: "Đăng nhập",
      passkey_added: "Thêm passkey",
      passkey_removed: "Xoá passkey",
      totp_enabled: "Bật ứng dụng Authenticator",
      totp_disabled: "Tắt ứng dụng Authenticator",
      backup_codes_new: "Tạo mã khôi phục mới",
      backup_code_used: "Dùng mã khôi phục",
    } as Record<string, string>,
    result: {
      done: "Đã lưu.",
      fresh: "Cần xác thực lại trước khi thay đổi.",
      wrong: "Mã không đúng.",
      last: "Không thể xoá cách xác thực cuối cùng.",
      failed: "Không thực hiện được.",
    } as Record<string, string>,
    back: "Về khu quản trị",
  },
};

const en: typeof vi = {
  signIn: {
    passkey: "Sign in with a passkey",
    passkeyHint: "Face ID, fingerprint or your device PIN.",
    passkeyFailed: "Passkey sign-in failed. Try again or use email.",
    codeTitle: "Got a 6-digit code by email?",
    codeHint: "For when you read the email on another device.",
    code: "Sign-in code",
    useCode: "Sign in with the code",
    codeWrong: "Wrong or expired code.",
    captcha: "Please confirm you are not a robot, then send again.",
    confirmTitle: "Confirm sign-in",
    confirmText: "Press the button to sign in on this device. The link works once, for 10 minutes.",
    confirm: "Sign in",
    confirmInvalid: "Invalid link. Ask for a new one.",
  },
  verify: {
    title: "Two-step verification",
    intro: "The admin area needs one more step for this session.",
    fresh: "This action needs you to verify again. Then do it once more.",
    passkey: "Verify with a passkey",
    totp: "Code from your authenticator app",
    totpSubmit: "Verify",
    backup: "Use a backup code",
    backupCode: "Backup code",
    backupSubmit: "Use backup code",
    wrong: "Wrong code. Try again.",
    locked: "Too many wrong codes. Locked for 15 minutes.",
    passkeyFailed: "Passkey verification failed.",
    signOut: "Sign out",
  },
  page: {
    title: "Account security",
    enrollNotice: "Staff accounts need two-step verification. Add a passkey (recommended) or an authenticator app to open the admin area.",
    freshNotice: "This change needs a verification within the last 10 minutes.",
    passkeys: "Passkeys",
    passkeysText: "Sign in with Face ID, fingerprint or your device PIN. Phishing-resistant. Add one on both your phone and computer.",
    addPasskey: "Add a passkey for this device",
    passkeyName: "Name (e.g. Lan's iPhone)",
    noPasskeys: "No passkeys yet.",
    remove: "Remove",
    removeAsk: "Remove this passkey?",
    lastFactor: "This is your last two-step method: add another before removing it.",
    totp: "Authenticator app",
    totpText: "Google Authenticator, Microsoft Authenticator, 1Password… show a 6-digit code every 30 seconds.",
    totpOn: "On",
    totpSetup: "Set up an authenticator app",
    totpScan: "Scan the QR code with the app, or type the key, then enter the 6-digit code to confirm.",
    totpKey: "Setup key",
    totpConfirm: "Confirm",
    totpDisable: "Turn off",
    totpDisableAsk: "Turn off the authenticator app?",
    backupCodes: "Backup codes",
    backupText: "Each code works once, if you lose your phone. Print them or keep them somewhere safe. Shown only once.",
    newBackupCodes: "Create new codes (old ones stop working)",
    devices: "Signed-in devices",
    thisDevice: "This device",
    signOutDevice: "Sign out",
    signOutOthers: "Sign out all other devices",
    since: "Since",
    activity: "Recent activity",
    events: {
      sign_in: "Sign-in",
      passkey_added: "Passkey added",
      passkey_removed: "Passkey removed",
      totp_enabled: "Authenticator app on",
      totp_disabled: "Authenticator app off",
      backup_codes_new: "New backup codes",
      backup_code_used: "Backup code used",
    },
    result: {
      done: "Saved.",
      fresh: "Verify again before changing this.",
      wrong: "Wrong code.",
      last: "You cannot remove your last two-step method.",
      failed: "Could not do that.",
    },
    back: "Back to admin",
  },
};

export const getSecurityContent = (locale: Locale) => (locale === "en" ? en : vi);
