import type { Locale } from "@/config/app";

/** Staff UI text for /admin/bookings and /admin/departures. */
const vi = {
  bookings: "Đơn đặt tour",
  departures: "Lịch khởi hành",
  source: "Nguồn",
  privateTour: "Tour riêng",
  allSources: "Mọi nguồn",
  sources: { website: "Website", phone: "Điện thoại", zalo: "Zalo", klook: "Klook", viator: "Viator", getyourguide: "GetYourGuide", other: "Khác" },
  newBooking: "+ Nhập booking",
  manual: {
    title: "Nhập booking (điện thoại, Zalo, OTA)",
    intro: "Dùng cho đơn đã thu tiền ngoài website. Số chỗ được trừ chung với đặt online nên không bán trùng.",
    departure: "Ngày khởi hành",
    noDepartures: "Chưa có ngày khởi hành nào đang mở trong 6 tháng tới.",
    name: "Họ tên khách",
    email: "Email (có thể bỏ trống)",
    phone: "Số điện thoại",
    adults: "Người lớn",
    children: "Trẻ em",
    infants: "Em bé",
    externalRef: "Mã đặt chỗ bên OTA",
    amount: "Số tiền thực thu (VND)",
    status: "Trạng thái",
    statusPaid: "Đã cọc",
    statusConfirmed: "Đã xác nhận (thanh toán đủ)",
    guestEmails: "Gửi email cho khách (xác nhận, nhắc lịch). OTA thường đã gửi voucher: để trống.",
    note: "Ghi chú (điểm đón, yêu cầu…)",
    submit: "Tạo booking",
    errors: { invalid: "Thông tin không hợp lệ.", required: "Vui lòng nhập thông tin này.", too_long: "Nội dung quá dài." } as Record<string, string>,
    soldOut: (n: number) => `Không đủ chỗ: ngày này chỉ còn ${n} chỗ.`,
    unavailable: "Ngày này đã đóng hoặc đã qua.",
  },
  detailSource: "Nguồn / mã OTA",
  noGuestEmails: "Không gửi email cho khách",
  stats: { paidToday: "Đơn cọc hôm nay", paidWeek: "Đơn cọc 7 ngày", depositsWeek: "Tiền cọc 7 ngày", attention: "Cần xử lý", upcoming: "Sắp khởi hành (7 ngày)", none: "Không có chuyến nào." },
  filters: { attention: "Cần xử lý", all: "Tất cả", held: "Đang giữ chỗ", expired: "Hết hạn", deposit_paid: "Đã cọc", refund_due: "Chờ hoàn tiền", confirmed: "Đã xác nhận", cancelled: "Đã huỷ" },
  search: "Mã đơn, tên, email, SĐT",
  tour: "Tour",
  allTours: "Tất cả tour",
  from: "Từ ngày",
  to: "Đến ngày",
  apply: "Lọc",
  columns: { code: "Mã", date: "Ngày đi", guest: "Khách", seats: "Chỗ", total: "Tổng", status: "Trạng thái" },
  refundOwed: "Nợ hoàn",
  empty: "Không có đơn nào.",
  previous: "Trước",
  next: "Sau",
  result: { done: "Đã lưu.", failed: "Không thực hiện được (trạng thái không cho phép hoặc dữ liệu không hợp lệ)." },
  detail: {
    back: "← Danh sách đơn",
    guest: "Khách",
    trip: "Chuyến đi",
    money: "Tiền",
    total: "Tổng",
    deposit: "Đặt cọc",
    paidAt: "Cọc lúc",
    rest: "Còn lại",
    refundDue: "Cần hoàn",
    refundedAt: "Đã hoàn lúc",
    payments: "Thanh toán VNPay",
    noPayments: "Chưa có lần thanh toán nào.",
    paymentCols: { txn: "Mã GD", amount: "Số tiền", status: "Trạng thái", bank: "Ngân hàng", at: "Thời gian" },
    guestNote: "Ghi chú của khách",
    staffNote: "Ghi chú nội bộ",
    saveNote: "Lưu ghi chú",
    actions: "Thao tác",
    confirm: "Xác nhận đơn",
    confirmAsk: "Xác nhận đơn này và gửi email cho khách?",
    cancel: "Huỷ đơn",
    cancelReason: "Lý do huỷ (gửi cho khách)",
    cancelRefund: "Hoàn tiền cọc cho khách",
    cancelAsk: "Huỷ đơn, nhả chỗ và gửi email cho khách?",
    refunded: "Đánh dấu đã hoàn tiền",
    refundNote: "Ghi chú hoàn tiền (mã GD hoàn, kênh…)",
    refundedAsk: "Xác nhận đã hoàn tiền cho khách?",
    history: "Nhật ký thao tác",
    noHistory: "Chưa có thao tác.",
    cancelledReason: "Lý do huỷ",
  },
  dep: {
    month: "Tháng",
    add: "Thêm ngày khởi hành",
    startDate: "Ngày bắt đầu",
    repeat: "Lặp vào các thứ (bỏ trống = chỉ 1 ngày)",
    weeks: "Số tuần",
    capacity: "Số chỗ",
    price: "Giá người lớn (VND, bỏ trống = giá tour)",
    addButton: "Thêm",
    cols: { date: "Ngày", tour: "Tour", sold: "Đã bán", held: "Đang giữ", capacity: "Số chỗ", price: "Giá", status: "Trạng thái" },
    save: "Lưu",
    open: "Mở",
    closed: "Đóng",
    listPrice: "giá tour",
    empty: "Không có ngày khởi hành trong khoảng này.",
    weekdays: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
  },
};

type AdminContent = typeof vi;

const en: AdminContent = {
  bookings: "Bookings",
  departures: "Departures",
  source: "Source",
  privateTour: "Private tour",
  allSources: "All sources",
  sources: { website: "Website", phone: "Phone", zalo: "Zalo", klook: "Klook", viator: "Viator", getyourguide: "GetYourGuide", other: "Other" },
  newBooking: "+ Add booking",
  manual: {
    title: "Add a booking (phone, Zalo, OTA)",
    intro: "For bookings paid outside the website. Seats are shared with online booking, so nothing is oversold.",
    departure: "Departure",
    noDepartures: "No open departures in the next 6 months.",
    name: "Guest name",
    email: "Email (optional)",
    phone: "Phone",
    adults: "Adults",
    children: "Children",
    infants: "Infants",
    externalRef: "OTA booking reference",
    amount: "Amount received (VND)",
    status: "Status",
    statusPaid: "Deposit paid",
    statusConfirmed: "Confirmed (paid in full)",
    guestEmails: "Email the guest (confirmation, reminder). OTAs usually send their own voucher: leave unchecked.",
    note: "Notes (pick-up, requests…)",
    submit: "Create booking",
    errors: { invalid: "Invalid value.", required: "Please fill in this field.", too_long: "Too long." } as Record<string, string>,
    soldOut: (n: number) => `Not enough seats: only ${n} left on this date.`,
    unavailable: "This date is closed or in the past.",
  },
  detailSource: "Source / OTA reference",
  noGuestEmails: "No emails to the guest",
  stats: { paidToday: "Deposits today", paidWeek: "Deposits (7 days)", depositsWeek: "Deposit total (7 days)", attention: "Needs action", upcoming: "Departing soon (7 days)", none: "No trips." },
  filters: { attention: "Needs action", all: "All", held: "On hold", expired: "Expired", deposit_paid: "Deposit paid", refund_due: "Refund due", confirmed: "Confirmed", cancelled: "Cancelled" },
  search: "Code, name, email, phone",
  tour: "Tour",
  allTours: "All tours",
  from: "From",
  to: "To",
  apply: "Filter",
  columns: { code: "Code", date: "Date", guest: "Guest", seats: "Seats", total: "Total", status: "Status" },
  refundOwed: "Refund owed",
  empty: "No bookings.",
  previous: "Previous",
  next: "Next",
  result: { done: "Saved.", failed: "Could not do that (status does not allow it or invalid data)." },
  detail: {
    back: "← All bookings",
    guest: "Guest",
    trip: "Trip",
    money: "Money",
    total: "Total",
    deposit: "Deposit",
    paidAt: "Paid at",
    rest: "Balance",
    refundDue: "Refund owed",
    refundedAt: "Refunded at",
    payments: "VNPay payments",
    noPayments: "No payment attempts yet.",
    paymentCols: { txn: "Txn ref", amount: "Amount", status: "Status", bank: "Bank", at: "Time" },
    guestNote: "Guest note",
    staffNote: "Staff note",
    saveNote: "Save note",
    actions: "Actions",
    confirm: "Confirm booking",
    confirmAsk: "Confirm this booking and email the guest?",
    cancel: "Cancel booking",
    cancelReason: "Reason (sent to the guest)",
    cancelRefund: "Refund the deposit",
    cancelAsk: "Cancel, release the seats and email the guest?",
    refunded: "Mark as refunded",
    refundNote: "Refund note (refund ref, channel…)",
    refundedAsk: "Confirm the guest has been refunded?",
    history: "Activity",
    noHistory: "No activity yet.",
    cancelledReason: "Cancellation reason",
  },
  dep: {
    month: "Month",
    add: "Add departures",
    startDate: "Start date",
    repeat: "Repeat on (leave empty = one date)",
    weeks: "Weeks",
    capacity: "Seats",
    price: "Adult price (VND, empty = tour price)",
    addButton: "Add",
    cols: { date: "Date", tour: "Tour", sold: "Sold", held: "On hold", capacity: "Seats", price: "Price", status: "Status" },
    save: "Save",
    open: "Open",
    closed: "Closed",
    listPrice: "tour price",
    empty: "No departures in this range.",
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  },
};

export function getBookingAdminContent(locale: Locale): AdminContent {
  return locale === "en" ? en : vi;
}
