import type { Locale } from "@/config/app";
import type { BookingFieldError } from "./service";

/** UI text for online booking (project-owned). */
const vi = {
  cta: "Đặt tour online",
  ctaHint: "Chọn ngày khởi hành, giữ chỗ ngay trong 15 phút.",
  pageTitle: (tour: string) => `Đặt tour: ${tour}`,
  departuresTitle: "Chọn ngày khởi hành",
  modeGroup: "Tour ghép",
  modePrivate: "Tour riêng",
  privateHint: "Xe, hướng dẫn viên và lịch trình riêng cho nhóm của bạn, khởi hành ngày bạn chọn.",
  privateFrom: (price: string) => `Tour riêng từ ${price}/khách`,
  privateCta: "Đặt tour riêng",
  privateDateTitle: "Chọn ngày đi",
  privateDate: "Ngày khởi hành",
  privateTiersTitle: "Giá mỗi khách theo số khách",
  tierLine: (from: number, to: number) => (from === to ? `${from} khách` : `${from}–${to} khách`),
  privateRange: (min: number, max: number) => `Tour riêng nhận từ ${min} đến ${max} khách (người lớn + trẻ em).`,
  noDepartures: "Hiện chưa có lịch khởi hành. Vui lòng gửi yêu cầu hoặc nhắn Zalo để chọn ngày riêng.",
  seatsLeft: (n: number) => (n <= 5 ? `Chỉ còn ${n} chỗ` : `Còn ${n} chỗ`),
  soldOut: "Hết chỗ",
  closed: "Đã đóng",
  tooSoon: "Hết hạn đặt",
  choose: "Chọn",
  chosen: "Đã chọn",
  formTitle: "Thông tin người đặt",
  name: "Họ tên",
  email: "Email",
  phone: "Số điện thoại / WhatsApp",
  adults: "Người lớn",
  children: "Trẻ em (5–10 tuổi)",
  infants: "Em bé (dưới 5 tuổi)",
  singleRooms: "Phòng đơn (phụ thu)",
  singleRoomsHint: (price: string) => `Phụ thu ${price}/phòng cho cả chuyến, nếu bạn muốn ngủ riêng.`,
  note: "Ghi chú (điểm đón, ăn chay…)",
  summary: "Tạm tính",
  steps: { label: "Tiến trình đặt tour", choose: "Chọn ngày & số khách", deposit: "Đặt cọc", confirmed: "Xác nhận" },
  guestsTitle: "Số khách",
  policyTitle: "Đặt cọc và huỷ",
  policy: [
    "Giữ chỗ 15 phút, chưa cần thanh toán.",
    "Đặt cọc 30% qua VNPay để giữ chỗ chắc chắn.",
    "Phần còn lại thanh toán trước ngày khởi hành.",
    "Huỷ trước 7 ngày: hoàn 100% tiền cọc.",
  ],
  policyLink: "Xem chính sách huỷ",
  nextStep: "Bước tiếp theo: đặt cọc qua VNPay trên trang đơn của bạn.",
  adultLine: (n: number) => `${n} người lớn`,
  childLine: (n: number, percent: number) => `${n} trẻ em (${percent}%)`,
  infantLine: (n: number, free: boolean) => `${n} em bé${free ? " (miễn phí)" : ""}`,
  singleLine: (n: number) => `${n} phòng đơn`,
  total: "Tổng tiền",
  deposit: "Đặt cọc (30%)",
  rest: "Thanh toán phần còn lại trước ngày đi",
  submit: "Giữ chỗ 15 phút",
  agree: { before: "Tôi đồng ý với ", terms: "điều khoản dịch vụ", and: " và ", cancellation: "chính sách huỷ / hoàn tiền", after: "." },
  sending: "Đang giữ chỗ…",
  vndNote: "Giá thanh toán bằng VND.",
  errors: {
    required: "Vui lòng nhập thông tin này.",
    invalid: "Thông tin không hợp lệ.",
    too_long: "Nội dung quá dài.",
    too_many: "Tối đa 10 khách (người lớn + trẻ em) mỗi đơn.",
    must_agree: "Vui lòng đồng ý với điều khoản và chính sách huỷ để tiếp tục.",
    sold_out: (n: number) => (n > 0 ? `Chỉ còn ${n} chỗ cho ngày này. Vui lòng giảm số khách hoặc chọn ngày khác.` : "Ngày này vừa hết chỗ. Vui lòng chọn ngày khác."),
    unavailable: "Ngày này không còn nhận đặt. Vui lòng chọn ngày khác.",
    rate_limited: "Bạn thao tác quá nhiều lần. Vui lòng thử lại sau ít phút hoặc nhắn Zalo cho chúng tôi.",
    error: "Không giữ được chỗ. Vui lòng thử lại.",
  } satisfies Record<BookingFieldError | "unavailable" | "rate_limited" | "error", string> & { sold_out: (n: number) => string },
  booking: {
    title: "Đơn đặt tour",
    code: "Mã đơn",
    tour: "Tour",
    date: "Ngày khởi hành",
    guests: "Số khách",
    contact: "Người đặt",
    heldTitle: "Đã giữ chỗ cho bạn",
    heldText: "Chỗ được giữ trong 15 phút. Hãy lưu lại đường link này để xem lại đơn.",
    remaining: "Thời gian giữ chỗ còn",
    pay: (amount: string) => `Đặt cọc ${amount} qua VNPay`,
    payHint: "Thẻ ATM nội địa, thẻ quốc tế hoặc QR ngân hàng. Chỗ chỉ được giữ chắc khi đặt cọc thành công.",
    transferChoose: "Chuyển khoản ngân hàng (VietQR)",
    transferHeldText: (until: string) => `Chỗ được giữ đến ${until} để bạn chuyển khoản. Hãy lưu lại đường link này để xem lại đơn.`,
    transferFailed: "Không chọn được chuyển khoản (có thể thời gian giữ chỗ đã hết). Hãy tải lại trang hoặc liên hệ chúng tôi.",
    transferChooseHint: "Giữ chỗ 2 giờ để bạn chuyển khoản; nhân viên xác nhận trong giờ làm việc.",
    transferTitle: "Chuyển khoản tiền cọc",
    transferText: "Quét mã bằng app ngân hàng: số tài khoản, số tiền và nội dung đã điền sẵn. Giữ nguyên nội dung chuyển khoản để chúng tôi nhận ra đơn của bạn.",
    transferQrLabel: (amount: string) => `Mã VietQR chuyển ${amount}`,
    transferBank: "Ngân hàng",
    transferAccount: "Số tài khoản",
    transferName: "Chủ tài khoản",
    transferAmount: "Số tiền",
    transferNote: "Nội dung",
    transferCopy: "Sao chép",
    transferCopied: "Đã chép",
    transferAfter: "Sau khi nhận được tiền (thường trong 30 phút, giờ làm việc 8:00–21:00), chúng tôi xác nhận và gửi email cho bạn. Trang này tự cập nhật.",
    transferDemo: "Tài khoản mẫu (chế độ thử): KHÔNG chuyển tiền thật.",
    transferOrPay: "Hoặc thanh toán online bằng VNPay:",
    payUnavailable: "Thanh toán online tạm thời chưa mở. Vui lòng liên hệ Zalo / hotline để đặt cọc.",
    confirming: "Đang xác nhận thanh toán với VNPay…",
    payFailed: "Thanh toán chưa thành công. Bạn có thể thử lại khi còn thời gian giữ chỗ.",
    paidTitle: "Đã nhận tiền đặt cọc",
    paidText: "Chỗ của bạn đã được giữ chắc chắn. Email xác nhận đã được gửi tới hộp thư của bạn.",
    refundTitle: "Chúng tôi sẽ hoàn tiền đặt cọc",
    refundText: "Tiền đến sau khi hết thời gian giữ chỗ và ngày này đã hết chỗ. Bắc Việt Travel sẽ liên hệ để hoàn tiền hoặc đổi ngày.",
    sandbox: "Chế độ thử nghiệm: thanh toán qua VNPay sandbox, không trừ tiền thật.",
    sandboxCard: "Thẻ test: ngân hàng NCB · 9704198526191432198 · NGUYEN VAN A · 07/15 · OTP 123456",
    returnTitle: "Kết quả thanh toán",
    returnNoLink: (code: string) => `Đơn ${code}: vui lòng mở lại đường link xem đơn (đã gửi qua email sau khi đặt cọc thành công).`,
    returnInvalid: "Không xác minh được kết quả thanh toán.",
    expiredTitle: "Đã hết thời gian giữ chỗ",
    expiredText: "Chỗ đã được nhả cho khách khác. Bạn có thể đặt lại nếu ngày này còn chỗ.",
    rebook: "Đặt lại",
    status: { held: "Đang giữ chỗ", expired: "Hết hạn", deposit_paid: "Đã đặt cọc", refund_due: "Chờ hoàn tiền", confirmed: "Đã xác nhận", cancelled: "Đã huỷ" },
    notFound: "Không tìm thấy đơn. Vui lòng kiểm tra lại đường link.",
    nextTitle: "Các bước tiếp theo",
    nextHeld: ["Đặt cọc qua VNPay trước khi hết thời gian giữ chỗ.", "Nhận email xác nhận kèm đường link xem đơn.", "Thanh toán phần còn lại trước ngày khởi hành."],
    nextPaid: ["Email xác nhận đã được gửi kèm đường link xem đơn.", "Trước ngày khởi hành, chúng tôi gửi lịch trình chi tiết và giờ đón qua Zalo hoặc email.", "Thanh toán phần còn lại trước ngày khởi hành."],
    helpTitle: "Cần hỗ trợ?",
    helpText: (code: string) => `Nhắn Zalo hoặc gọi hotline, đọc mã đơn ${code}.`,
  },
};

type BookingContent = typeof vi;

const en: BookingContent = {
  cta: "Book online",
  ctaHint: "Pick a departure date and hold your seats for 15 minutes.",
  pageTitle: (tour) => `Book: ${tour}`,
  departuresTitle: "Choose a departure date",
  modeGroup: "Group tour",
  modePrivate: "Private tour",
  privateHint: "Your own vehicle, guide and pace, on the date you choose.",
  privateFrom: (price) => `Private tour from ${price} per guest`,
  privateCta: "Book a private tour",
  privateDateTitle: "Choose your date",
  privateDate: "Departure date",
  privateTiersTitle: "Price per guest by group size",
  tierLine: (from, to) => (from === to ? `${from} guests` : `${from}–${to} guests`),
  privateRange: (min, max) => `Private tours take ${min} to ${max} guests (adults + children).`,
  noDepartures: "No scheduled departures right now. Send us a request or message us on WhatsApp for a private date.",
  seatsLeft: (n) => (n <= 5 ? `Only ${n} left` : `${n} seats left`),
  soldOut: "Sold out",
  closed: "Closed",
  tooSoon: "Booking closed",
  choose: "Select",
  chosen: "Selected",
  formTitle: "Your details",
  name: "Full name",
  email: "Email",
  phone: "Phone / WhatsApp",
  adults: "Adults",
  children: "Children (5–10)",
  infants: "Infants (under 5)",
  singleRooms: "Single rooms (supplement)",
  singleRoomsHint: (price) => `${price} per room for the whole trip, if you prefer a room to yourself.`,
  note: "Notes (hotel pick-up, dietary needs…)",
  summary: "Estimate",
  steps: { label: "Booking progress", choose: "Date & travellers", deposit: "Deposit", confirmed: "Confirmed" },
  guestsTitle: "Travellers",
  policyTitle: "Deposit and cancellation",
  policy: [
    "Seats held for 15 minutes, no payment yet.",
    "Pay a 30% deposit by VNPay to secure your seats.",
    "The balance is paid before departure.",
    "Cancel 7+ days before departure: full deposit refunded.",
  ],
  policyLink: "Read the cancellation policy",
  nextStep: "Next: pay the deposit by VNPay on your booking page.",
  adultLine: (n) => `${n} adult${n > 1 ? "s" : ""}`,
  childLine: (n, percent) => `${n} child${n > 1 ? "ren" : ""} (${percent}%)`,
  infantLine: (n, free) => `${n} infant${n > 1 ? "s" : ""}${free ? " (free)" : ""}`,
  singleLine: (n) => `${n} single room${n > 1 ? "s" : ""}`,
  total: "Total",
  deposit: "Deposit (30%)",
  rest: "Pay the balance before departure",
  submit: "Hold seats for 15 minutes",
  agree: { before: "I accept the ", terms: "terms of service", and: " and the ", cancellation: "cancellation & refund policy", after: "." },
  sending: "Holding seats…",
  vndNote: "Charged in Vietnamese dong (VND).",
  errors: {
    required: "Please fill in this field.",
    invalid: "Please check this value.",
    too_long: "Text is too long.",
    too_many: "Up to 10 guests (adults + children) per booking.",
    must_agree: "Please accept the terms and the cancellation policy to continue.",
    sold_out: (n) => (n > 0 ? `Only ${n} seats left on this date. Reduce the group or choose another date.` : "This date just sold out. Please choose another date."),
    unavailable: "This date is no longer bookable. Please choose another date.",
    rate_limited: "Too many attempts. Please try again in a few minutes or message us on WhatsApp.",
    error: "Could not hold your seats. Please try again.",
  },
  booking: {
    title: "Your booking",
    code: "Booking code",
    tour: "Tour",
    date: "Departure",
    guests: "Guests",
    contact: "Booked by",
    heldTitle: "Your seats are on hold",
    heldText: "We hold your seats for 15 minutes. Keep this link to view your booking again.",
    remaining: "Hold time left",
    pay: (amount) => `Pay ${amount} deposit with VNPay`,
    payHint: "Vietnamese ATM cards, international cards or bank QR. Seats are secured once the deposit is paid.",
    transferChoose: "Bank transfer (VietQR)",
    transferHeldText: (until: string) => `Your seats are held until ${until} (Vietnam time) for the transfer. Keep this link to view your booking again.`,
    transferFailed: "Could not switch to bank transfer (your hold may have run out). Reload the page or contact us.",
    transferChooseHint: "Seats held for 2 hours while you transfer; our team confirms during business hours.",
    transferTitle: "Transfer the deposit",
    transferText: "Scan the code with a Vietnamese banking app: account, amount and reference are filled in. Keep the reference so we can match your booking.",
    transferQrLabel: (amount: string) => `VietQR code to transfer ${amount}`,
    transferBank: "Bank",
    transferAccount: "Account number",
    transferName: "Account holder",
    transferAmount: "Amount",
    transferNote: "Reference",
    transferCopy: "Copy",
    transferCopied: "Copied",
    transferAfter: "Once the money arrives (usually within 30 minutes, 8:00–21:00 Vietnam time) we confirm and email you. This page updates by itself.",
    transferDemo: "Demo account (test mode): do NOT send real money.",
    transferOrPay: "Or pay online with VNPay:",
    payUnavailable: "Online payment is not open yet. Please contact us on WhatsApp to pay the deposit.",
    confirming: "Confirming your payment with VNPay…",
    payFailed: "The payment did not go through. You can try again while your hold lasts.",
    paidTitle: "Deposit received",
    paidText: "Your seats are secured. A confirmation email is on its way.",
    refundTitle: "Your deposit will be refunded",
    refundText: "The payment arrived after your hold expired and the date sold out. We will contact you to refund or move to another date.",
    sandbox: "Test mode: payments go through the VNPay sandbox, no real money is charged.",
    sandboxCard: "Test card: NCB bank · 9704198526191432198 · NGUYEN VAN A · 07/15 · OTP 123456",
    returnTitle: "Payment result",
    returnNoLink: (code) => `Booking ${code}: please open your booking link again (emailed after a successful deposit).`,
    returnInvalid: "We could not verify this payment result.",
    expiredTitle: "Your hold has expired",
    expiredText: "The seats were released. You can book again if the date still has seats.",
    rebook: "Book again",
    status: { held: "On hold", expired: "Expired", deposit_paid: "Deposit paid", refund_due: "Refund due", confirmed: "Confirmed", cancelled: "Cancelled" },
    notFound: "Booking not found. Please check your link.",
    nextTitle: "What happens next",
    nextHeld: ["Pay the deposit by VNPay before the hold runs out.", "You receive a confirmation email with the link to this page.", "The balance is paid before departure."],
    nextPaid: ["A confirmation email with the link to this page has been sent.", "Before departure we send the detailed itinerary and pick-up time by WhatsApp or email.", "The balance is paid before departure."],
    helpTitle: "Need help?",
    helpText: (code: string) => `Message us on WhatsApp or call the hotline with your booking code ${code}.`,
  },
};

export function getBookingContent(locale: Locale): BookingContent {
  return locale === "en" ? en : vi;
}

export const formatVnd = (n: number, locale: Locale) =>
  new Intl.NumberFormat(locale === "vi" ? "vi-VN" : "en-US", { style: "currency", currency: "VND", maximumFractionDigits: 0 }).format(n);

/** "Thứ Sáu, 09/10/2026" / "Fri, 9 Oct 2026" — dates are calendar days, formatted in UTC so they never shift. */
export const formatDay = (day: string, locale: Locale) =>
  new Intl.DateTimeFormat(locale === "vi" ? "vi-VN" : "en-GB", { weekday: locale === "vi" ? "long" : "short", day: "numeric", month: locale === "vi" ? "2-digit" : "short", year: "numeric", timeZone: "UTC" }).format(new Date(`${day}T00:00:00Z`));
