import type { Locale } from "@/config/app";
import type { Destination } from "./tours/catalog";

/** Project-owned UI text for tour pages (starter text lives in content/). */
const vi = {
  nav: { tours: "Tour" },
  destinations: {
    "ha-long": { name: "Vịnh Hạ Long", tagline: "Di sản thiên nhiên thế giới, ngủ đêm trên du thuyền giữa hàng nghìn đảo đá vôi." },
    "ninh-binh": { name: "Ninh Bình", tagline: "“Hạ Long trên cạn”: đi thuyền qua hang động Tràng An, ngắm Tam Cốc từ đỉnh Hang Múa." },
    sapa: { name: "Sapa", tagline: "Ruộng bậc thang, bản làng dân tộc và đỉnh Fansipan 3.143 m." },
  } satisfies Record<Destination, { name: string; tagline: string }>,
  home: {
    destinationsTitle: "Điểm đến miền Bắc",
    featuredTitle: "Tour được đặt nhiều",
    whyTitle: "Vì sao chọn Bắc Việt Travel",
    why: [
      { title: "Giá minh bạch", description: "Báo giá trọn gói, ghi rõ bao gồm và không bao gồm. Không phát sinh." },
      { title: "Hướng dẫn viên địa phương", description: "Người bản địa dẫn đường, nói tiếng Việt và tiếng Anh." },
      { title: "Nhóm nhỏ", description: "Tối đa 12–16 khách mỗi đoàn để chuyến đi thoải mái." },
      { title: "Hỗ trợ 24/7", description: "Liên hệ ngay qua Zalo, WhatsApp hoặc hotline trong suốt chuyến đi." },
    ],
    reviewsTitle: "Khách hàng nói gì",
    reviewsDemo: "Đánh giá minh hoạ. Sẽ thay bằng đánh giá thật từ Tripadvisor và Google.",
    reviewsSummary: { rating: "4,9/5", count: "trên 320 đánh giá" },
    reviews: [
      { name: "Nguyễn Thu Lan", origin: "Hà Nội", source: "Google", date: "Tháng 9/2026", tour: "Du thuyền Hạ Long 2 ngày 1 đêm", text: "Du thuyền sạch sẽ, đồ ăn ngon, hướng dẫn viên Hùng rất nhiệt tình và chu đáo với hai bé nhà mình. Buổi chèo kayak hang Luồn là phần cả nhà thích nhất." },
      { name: "Mark Thompson", origin: "Australia", source: "Tripadvisor", date: "Tháng 8/2026", tour: "Tràng An – Hang Múa trong ngày", text: "The Trang An boat ride was the highlight of our trip to Vietnam. Pick-up on time, small group, and our guide knew every cave by name." },
      { name: "Trần Minh Tuấn", origin: "TP. Hồ Chí Minh", source: "Google", date: "Tháng 7/2026", tour: "Trekking Sapa 2 ngày 1 đêm", text: "Cung trek vừa sức, homestay ấm cúng, cảnh ruộng bậc thang mùa nước đổ tuyệt đẹp. Đặt online giữ chỗ nhanh, được xác nhận qua Zalo trong 10 phút." },
    ],
    viewAll: "Xem tất cả tour",
    search: {
      title: "Tìm tour",
      destination: "Điểm đến",
      anyDestination: "Tất cả điểm đến",
      date: "Ngày đi",
      guests: "Số khách",
      submit: "Tìm tour",
    },
    trust: [
      { icon: "license", label: "Giấy phép lữ hành quốc tế" },
      { icon: "pickup", label: "Đón tận nơi ở phố cổ Hà Nội" },
      { icon: "payment", label: "Thanh toán an toàn qua VNPay" },
      { icon: "support", label: "Hỗ trợ 24/7 qua Zalo" },
    ],
    private: {
      eyebrow: "Tour riêng theo yêu cầu",
      title: "Gia đình, nhóm bạn hay công ty: lịch trình của riêng bạn",
      text: "Xe và hướng dẫn viên riêng, chọn ngày khởi hành, thêm bớt điểm tham quan. Giá theo số khách, báo giá trong 2 giờ làm việc.",
      points: ["Xe đời mới, tài xế kinh nghiệm", "Hướng dẫn viên nói tiếng Anh", "Linh hoạt giờ đón và nhịp đi"],
      cta: "Nhận báo giá tour riêng",
    },
    blogTitle: "Cẩm nang du lịch miền Bắc",
    blogAll: "Xem tất cả bài viết",
    contactTitle: "Cần tư vấn lịch trình?",
    contactText: "Gửi câu hỏi cho chúng tôi, hoặc nhắn Zalo để được trả lời ngay.",
  },
  tours: {
    title: "Tour du lịch miền Bắc",
    subtitle: "Hạ Long, Ninh Bình, Sapa: khởi hành từ Hà Nội, có xe đón tận nơi.",
    destinationTitle: (name: string) => `Tour ${name}`,
    allDestinationsLink: "Tất cả điểm đến",
    filters: {
      title: "Lọc tour",
      destination: "Điểm đến",
      any: "Tất cả",
      duration: "Số ngày",
      durations: { "1": "1 ngày", "2": "2 ngày", "3+": "Từ 3 ngày" },
      price: "Mức giá",
      prices: { low: "Dưới 1,5 triệu", mid: "1,5 – 3 triệu", high: "Từ 3 triệu" },
      type: "Loại tour",
      types: { group: "Tour ghép", private: "Có tour riêng" },
      sort: "Sắp xếp",
      sorts: { popular: "Phổ biến", "price-asc": "Giá thấp đến cao", "price-desc": "Giá cao đến thấp", duration: "Ngắn ngày trước" },
      apply: "Áp dụng",
      reset: "Xoá bộ lọc",
      count: (n: number) => `${n} tour`,
      empty: "Chưa có tour phù hợp. Thử bỏ bớt bộ lọc, hoặc nhắn Zalo để chúng tôi thiết kế tour riêng.",
      trip: (date: string | undefined, guests: number | undefined) => [date && `Ngày đi ${date.split("-").reverse().join("/")}`, guests && `${guests} khách`].filter(Boolean).join(" · "),
    },
    from: "Từ",
    perPerson: "/ khách",
    days: (d: number, n: number) => (n > 0 ? `${d} ngày ${n} đêm` : `${d} ngày`),
    viewTour: "Xem chi tiết",
    highlights: "Điểm nổi bật",
    itinerary: "Lịch trình",
    day: "Ngày",
    includes: "Giá bao gồm",
    excludes: "Không bao gồm",
    departure: "Khởi hành",
    groupSize: "Quy mô đoàn",
    duration: "Thời gian",
    related: "Tour cùng điểm đến",
    priceNote: "Giá tham khảo cho đoàn 2 khách trở lên; giá cuối cùng tuỳ ngày khởi hành.",
    allDestinations: "Tất cả",
    gallery: "Ảnh tour",
    galleryLabels: {
      viewAll: (n: number) => `Xem ${n} ảnh`,
      close: "Đóng",
      previous: "Ảnh trước",
      next: "Ảnh sau",
      photo: (i: number, n: number) => `Ảnh ${i}/${n}`,
    },
    languages: "Ngôn ngữ",
    languagesValue: "Tiếng Việt, English",
    departuresTitle: "Lịch khởi hành",
    departuresHint: "Số chỗ cập nhật theo thời gian thực. Chọn ngày để giữ chỗ.",
    departuresAll: "Xem tất cả ngày",
    chooseDate: "Chọn ngày và đặt",
    bookDate: (date: string) => `Đặt ngày ${date}`,
    chooseDay: (date: string) => `Chọn ${date}`,
    askAdvice: "Hỏi tư vấn trước khi đặt",
    trust: ["Giữ chỗ 15 phút, chưa cần thanh toán", "Cọc 30% qua VNPay hoặc chuyển khoản", "Huỷ trước 7 ngày: hoàn cọc 100%"],
    itineraryDay: (n: number) => `Ngày ${n}`,
  },
  inquiry: {
    title: "Gửi yêu cầu đặt tour",
    subtitle: "Miễn phí, không cần thanh toán trước. Chúng tôi liên hệ lại trong 24 giờ.",
    name: "Họ tên",
    email: "Email",
    phone: "Số điện thoại / WhatsApp",
    channel: "Liên hệ với tôi qua",
    channels: { zalo: "Zalo", whatsapp: "WhatsApp", phone: "Điện thoại", email: "Email" },
    date: "Ngày khởi hành",
    datePlaceholder: "Chọn ngày",
    adults: "Người lớn",
    children: "Trẻ em",
    note: "Ghi chú (yêu cầu ăn uống, đón tại khách sạn…)",
    submit: "Gửi yêu cầu",
    sending: "Đang gửi…",
    success: "Đã gửi! Chúng tôi sẽ liên hệ lại trong 24 giờ. Email xác nhận đã được gửi tới hộp thư của bạn.",
    errors: {
      required: "Vui lòng nhập thông tin này.",
      invalid_email: "Email không hợp lệ.",
      invalid_phone: "Số điện thoại không hợp lệ.",
      invalid_date: "Ngày không hợp lệ.",
      past_date: "Vui lòng chọn ngày từ hôm nay trở đi.",
      invalid_number: "Số lượng không hợp lệ.",
      too_long: "Nội dung quá dài.",
      rate_limited: "Bạn gửi quá nhiều lần. Vui lòng thử lại sau ít phút hoặc nhắn Zalo cho chúng tôi.",
      error: "Không gửi được. Vui lòng thử lại hoặc liên hệ qua Zalo / hotline.",
    },
  },
  header: {
    home: "Bắc Việt Travel, về trang chủ",
    nav: "Menu chính",
    destinations: "Điểm đến",
    allTours: "Tất cả tour",
    privateTours: "Tour riêng",
    guide: "Cẩm nang",
    advice: "Tư vấn",
    book: "Đặt tour",
    pickup: "Đón tận nơi ở Hà Nội",
    call: "Gọi hotline",
  },
  footerNav: { tours: "Tour", company: "Công ty", policies: "Chính sách", rights: "Bảo lưu mọi quyền." },
  contact: {
    title: "Liên hệ nhanh",
    zalo: "Chat Zalo",
    whatsapp: "WhatsApp",
    call: "Gọi hotline",
    email: "Email",
    whatsappText: (tour?: string) => (tour ? `Xin chào, tôi muốn hỏi về tour "${tour}".` : "Xin chào, tôi muốn được tư vấn tour."),
    license: "Giấy phép lữ hành",
  },
  footer: {
    nav: "Thông tin và chính sách",
    taxCode: "MST",
    representative: "Người đại diện",
    address: "Địa chỉ",
    hotline: "Hotline",
    hours: "Giờ làm việc",
    about: "Giới thiệu",
    cancellation: "Chính sách huỷ / hoàn tiền",
    payment: "Chính sách thanh toán",
    privacy: "Chính sách bảo mật",
    terms: "Điều khoản dịch vụ",
    moit: "Đã thông báo Bộ Công Thương",
  },
  credits: { title: "Nguồn ảnh", text: "Ảnh minh hoạ từ Unsplash (Unsplash License)." },
};

type ProductContent = typeof vi;

const en: ProductContent = {
  nav: { tours: "Tours" },
  destinations: {
    "ha-long": { name: "Ha Long Bay", tagline: "UNESCO World Heritage: sleep on a cruise among thousands of limestone islands." },
    "ninh-binh": { name: "Ninh Binh", tagline: "“Ha Long Bay on land”: row through the caves of Trang An and climb Mua Cave for the view." },
    sapa: { name: "Sapa", tagline: "Rice terraces, ethnic minority villages and Fansipan, the 3,143 m roof of Indochina." },
  },
  home: {
    destinationsTitle: "Northern Vietnam destinations",
    featuredTitle: "Most booked tours",
    whyTitle: "Why travel with Bac Viet Travel",
    why: [
      { title: "Transparent prices", description: "All-inclusive quotes with clear inclusions and exclusions. No surprises." },
      { title: "Local guides", description: "Guides from the region, speaking Vietnamese and English." },
      { title: "Small groups", description: "12–16 travellers at most, for a relaxed trip." },
      { title: "24/7 support", description: "Reach us on WhatsApp, Zalo or by phone during your trip." },
    ],
    reviewsTitle: "What travellers say",
    reviewsDemo: "Sample reviews. They will be replaced by real Tripadvisor and Google reviews.",
    reviewsSummary: { rating: "4.9/5", count: "from 320+ reviews" },
    reviews: [
      { name: "Mark Thompson", origin: "Australia", source: "Tripadvisor", date: "August 2026", tour: "Trang An & Mua Cave day trip", text: "The Trang An boat ride was the highlight of our trip to Vietnam. Pick-up on time, small group, and our guide knew every cave by name." },
      { name: "Sophie Laurent", origin: "France", source: "Google", date: "September 2026", tour: "Sapa trekking 2 days 1 night", text: "The trek was just the right level and the homestay family was so welcoming. Booking online took two minutes and WhatsApp replies were instant." },
      { name: "Nguyen Thu Lan", origin: "Hanoi", source: "Google", date: "September 2026", tour: "Ha Long Bay cruise 2 days 1 night", text: "Clean cruise, great food and a very caring guide with our two kids. Kayaking through Luon Cave was everyone's favourite." },
    ],
    viewAll: "See all tours",
    search: {
      title: "Find a tour",
      destination: "Destination",
      anyDestination: "All destinations",
      date: "Date",
      guests: "Travellers",
      submit: "Search tours",
    },
    trust: [
      { icon: "license", label: "Licensed international tour operator" },
      { icon: "pickup", label: "Free pick-up in Hanoi Old Quarter" },
      { icon: "payment", label: "Secure payment with VNPay" },
      { icon: "support", label: "24/7 support on WhatsApp" },
    ],
    private: {
      eyebrow: "Private tours",
      title: "Family, friends or company: a trip on your own schedule",
      text: "Your own vehicle and guide, your departure date, stops added or skipped. Priced by group size, quoted within 2 working hours.",
      points: ["Recent vehicles, experienced drivers", "English-speaking guides", "Flexible pick-up time and pace"],
      cta: "Get a private tour quote",
    },
    blogTitle: "Northern Vietnam travel guides",
    blogAll: "All articles",
    contactTitle: "Planning your trip?",
    contactText: "Send us your questions, or message us on WhatsApp for an instant reply.",
  },
  tours: {
    title: "Northern Vietnam tours",
    subtitle: "Ha Long Bay, Ninh Binh and Sapa: departing from Hanoi with hotel pick-up.",
    destinationTitle: (name: string) => `${name} tours`,
    allDestinationsLink: "All destinations",
    filters: {
      title: "Filter tours",
      destination: "Destination",
      any: "Any",
      duration: "Length",
      durations: { "1": "1 day", "2": "2 days", "3+": "3 days or more" },
      price: "Price",
      prices: { low: "Under $60", mid: "$60 – 120", high: "$120 and up" },
      type: "Tour type",
      types: { group: "Group tours", private: "Private available" },
      sort: "Sort by",
      sorts: { popular: "Most popular", "price-asc": "Price: low to high", "price-desc": "Price: high to low", duration: "Shortest first" },
      apply: "Apply",
      reset: "Clear filters",
      count: (n: number) => `${n} tour${n === 1 ? "" : "s"}`,
      empty: "No tours match yet. Remove a filter, or message us on WhatsApp for a private itinerary.",
      trip: (date: string | undefined, guests: number | undefined) =>
        [date && `Date ${new Date(`${date}T00:00:00Z`).toLocaleDateString("en-GB", { day: "numeric", month: "short", timeZone: "UTC" })}`, guests && `${guests} traveller${guests === 1 ? "" : "s"}`].filter(Boolean).join(" · "),
    },
    from: "From",
    perPerson: "/ person",
    days: (d: number, n: number) => (n > 0 ? `${d} days ${n} night${n > 1 ? "s" : ""}` : `${d} day${d > 1 ? "s" : ""}`),
    viewTour: "View tour",
    highlights: "Highlights",
    itinerary: "Itinerary",
    day: "Day",
    includes: "Included",
    excludes: "Not included",
    departure: "Departure",
    groupSize: "Group size",
    duration: "Duration",
    related: "More tours in this destination",
    priceNote: "Indicative price for groups of 2 or more; final price depends on the departure date.",
    allDestinations: "All",
    gallery: "Tour photos",
    galleryLabels: {
      viewAll: (n: number) => `See all ${n} photos`,
      close: "Close",
      previous: "Previous photo",
      next: "Next photo",
      photo: (i: number, n: number) => `Photo ${i} of ${n}`,
    },
    languages: "Languages",
    languagesValue: "English, Vietnamese",
    departuresTitle: "Departure dates",
    departuresHint: "Seats update live. Pick a date to hold your seats.",
    departuresAll: "See all dates",
    chooseDate: "Choose a date and book",
    bookDate: (date: string) => `Book ${date}`,
    chooseDay: (date: string) => `Choose ${date}`,
    askAdvice: "Ask us before booking",
    trust: ["Seats held 15 minutes, no payment yet", "30% deposit by VNPay or bank transfer", "Cancel 7+ days ahead: full deposit back"],
    itineraryDay: (n: number) => `Day ${n}`,
  },
  inquiry: {
    title: "Request this tour",
    subtitle: "Free and no payment needed now. We reply within 24 hours.",
    name: "Full name",
    email: "Email",
    phone: "Phone / WhatsApp",
    channel: "Contact me via",
    channels: { zalo: "Zalo", whatsapp: "WhatsApp", phone: "Phone call", email: "Email" },
    date: "Departure date",
    datePlaceholder: "Pick a date",
    adults: "Adults",
    children: "Children",
    note: "Notes (dietary needs, hotel pick-up…)",
    submit: "Send request",
    sending: "Sending…",
    success: "Sent! We will get back to you within 24 hours. A confirmation email is on its way.",
    errors: {
      required: "Please fill in this field.",
      invalid_email: "Invalid email address.",
      invalid_phone: "Invalid phone number.",
      invalid_date: "Invalid date.",
      past_date: "Please choose today or a later date.",
      invalid_number: "Invalid number.",
      too_long: "Too long.",
      rate_limited: "Too many requests. Please try again in a few minutes or message us on WhatsApp.",
      error: "Could not send. Please try again or contact us on WhatsApp.",
    },
  },
  header: {
    home: "Bắc Việt Travel, home",
    nav: "Main menu",
    destinations: "Destinations",
    allTours: "All tours",
    privateTours: "Private tours",
    guide: "Travel guide",
    advice: "Advice",
    book: "Book a tour",
    pickup: "Hotel pickup in Hanoi",
    call: "Call us",
  },
  footerNav: { tours: "Tours", company: "Company", policies: "Policies", rights: "All rights reserved." },
  contact: {
    title: "Quick contact",
    zalo: "Zalo",
    whatsapp: "Chat on WhatsApp",
    call: "Call us",
    email: "Email",
    whatsappText: (tour?: string) => (tour ? `Hello, I would like to ask about the tour "${tour}".` : "Hello, I would like some advice on a tour."),
    license: "Tour operator licence",
  },
  footer: {
    nav: "Company and policies",
    taxCode: "Tax code",
    representative: "Legal representative",
    address: "Address",
    hotline: "Hotline",
    hours: "Opening hours",
    about: "About us",
    cancellation: "Cancellation & refund policy",
    payment: "Payment policy",
    privacy: "Privacy policy",
    terms: "Terms of service",
    moit: "Registered with the Ministry of Industry and Trade",
  },
  credits: { title: "Photo credits", text: "Illustrative photos from Unsplash (Unsplash License)." },
};

const content: Record<Locale, ProductContent> = { vi, en };

export function getProductContent(locale: Locale): ProductContent {
  return content[locale];
}
export type { ProductContent };
