import type { ImgHTMLAttributes } from "react";

export interface MediaImageProps extends Omit<ImgHTMLAttributes<HTMLImageElement>, "src" | "srcSet" | "width" | "height"> {
  /** From `media.imageProps(asset, …)`. */
  image: { src: string; srcSet: string; width: number; height: number };
  alt: string;
  /** e.g. "(min-width: 768px) 50vw, 100vw". */
  sizes: string;
}

/** Responsive image from the media CDN (resized and converted there, not by Next's image optimizer). */
export function MediaImage({ image, alt, sizes, loading = "lazy", ...rest }: MediaImageProps) {
  // eslint-disable-next-line @next/next/no-img-element -- srcSet is generated by the media provider
  return <img src={image.src} srcSet={image.srcSet} sizes={sizes} width={image.width} height={image.height} alt={alt} loading={loading} decoding="async" {...rest} />;
}
