import type { AppContent } from "../app-types";

export const app: AppContent = {
  login: {
    title: "Sign in",
    subtitle: "Get a sign-in link by email. No password needed.",
    email: "Email",
    sendLink: "Send sign-in link",
    sending: "Sending…",
    linkSent: "Sent! Check your inbox and click the link to sign in.",
    or: "or",
    google: "Continue with Google",
    errors: {
      invalid_email: "Please enter a valid email.",
      rate_limited: "Too many requests. Please try again in a few minutes.",
      error: "Could not send the link. Please try again.",
      link: "This sign-in link is invalid or has expired. Please request a new one.",
    },
  },
  dashboard: {
    nav: { overview: "Overview", account: "Account" },
    signOut: "Sign out",
    welcome: "Welcome",
    overviewText: "This is the sample dashboard. The product area lives under Notes.",
  },
  account: {
    title: "Account",
    profile: "Profile",
    exportTitle: "Export data",
    exportText: "Download all your data as JSON.",
    exportButton: "Download",
    deleteTitle: "Delete account",
    deleteText: "Permanently delete your account and all data. This cannot be undone.",
    deleteConfirmLabel: "Type your email to confirm",
    deleteButton: "Delete account",
  },
  billing: {
    title: "Plan",
    currentPlan: "Current plan",
    activeUntil: "Active until",
    renewsAutomatically: "Renews automatically via Polar",
    upgradeTitle: "Upgrade or extend Pro",
    monthly: "1 month",
    yearly: "1 year",
    payInternational: "International card (Polar, auto-renew)",
    payVietnam: "VNPay (one-time payment)",
    vietnamNote: "VNPay payments add time to your current plan and never charge automatically.",
    manage: "Manage subscription on Polar",
    pricingTitle: "Pricing",
    pricingSubtitle: "Start free, upgrade when you need more.",
    perMonth: "/ month",
    perYear: "/ year",
    choosePlan: "Choose plan",
    returnPaid: "Payment successful. Pro is now active.",
    returnPending: "Waiting for VNPay to confirm the payment. Please refresh in a few minutes.",
    returnFailed: "The payment did not go through. You were not charged for this plan.",
    returnInvalid: "The payment result could not be verified.",
    backToBilling: "Back to billing",
    checkoutSuccess: "Thank you! Your plan will be active in a moment.",
    error: "Could not start the payment. Please try again.",
  },
  legal: {
    terms: "Terms of Service",
    privacy: "Privacy Policy",
    lastUpdated: "Last updated",
    templateNotice: "This is a template. Replace it with legal text appropriate for your business.",
  },
};
