import type { AppContent } from "../app-types";

export const app: AppContent = {
  login: {
    title: "Sign in",
    subtitle: "Get a sign-in link by email. No password needed.",
    email: "Email",
    sendLink: "Send sign-in link",
    sending: "Sending…",
    linkSent: "Sent! Check your inbox and click the link to sign in.",
    or: "or",
    google: "Continue with Google",
    errors: {
      invalid_email: "Please enter a valid email.",
      rate_limited: "Too many requests. Please try again in a few minutes.",
      error: "Could not send the link. Please try again.",
      link: "This sign-in link is invalid or has expired. Please request a new one.",
    },
  },
  dashboard: {
    nav: { overview: "Overview", account: "Account", admin: "Admin" },
    shell: { menu: "Menu", toggle: "Toggle menu", skip: "Skip to main content", breadcrumb: "Breadcrumb" },
    signOut: "Sign out",
    welcome: "Welcome",
    overviewText: "This is the sample dashboard. The product area lives under Notes.",
  },
  account: {
    title: "Account",
    profile: "Profile",
    exportTitle: "Export data",
    exportText: "Download all your data as JSON.",
    exportButton: "Download",
    deleteTitle: "Delete account",
    deleteText: "Permanently delete your account and all data. This cannot be undone.",
    deleteConfirmLabel: "Type your email to confirm",
    deleteButton: "Delete account",
  },
  billing: {
    title: "Plan",
    currentPlan: "Current plan",
    activeUntil: "Active until",
    renewsAutomatically: "Renews automatically via Polar",
    upgradeTitle: "Upgrade or extend Pro",
    monthly: "1 month",
    yearly: "1 year",
    payInternational: "International card (Polar, auto-renew)",
    payVietnam: "VNPay (one-time payment)",
    vietnamNote: "VNPay payments add time to your current plan and never charge automatically.",
    manage: "Manage subscription on Polar",
    pricingTitle: "Pricing",
    pricingSubtitle: "Start free, upgrade when you need more.",
    perMonth: "/ month",
    perYear: "/ year",
    choosePlan: "Choose plan",
    returnPaid: "Payment successful. Pro is now active.",
    returnPending: "Waiting for VNPay to confirm the payment. Please refresh in a few minutes.",
    returnFailed: "The payment did not go through. You were not charged for this plan.",
    returnInvalid: "The payment result could not be verified.",
    backToBilling: "Back to billing",
    checkoutSuccess: "Thank you! Your plan will be active in a moment.",
    error: "Could not start the payment. Please try again.",
    rateLimited: "Too many attempts. Please wait a few minutes and try again.",
  },
  legal: {
    terms: "Terms of Service",
    privacy: "Privacy Policy",
    lastUpdated: "Last updated",
    templateNotice: "This is a template. Replace it with legal text appropriate for your business.",
  },
  files: {
    title: "My files",
    usage: "Used",
    upload: "Upload a file",
    uploading: "Uploading…",
    allowed: "Images, PDF, text. Up to",
    empty: "No files yet.",
    download: "Download",
    delete: "Delete",
    errors: {
      type: "This file type is not supported.",
      size: "The file is too large.",
      quota: "You are out of storage. Upgrade your plan for more.",
      failed: "Upload failed. Please try again.",
    },
  },
  consent: {
    text: "We use first-party analytics (never shared with third parties) to improve this site. Do you agree?",
    accept: "Accept",
    decline: "Decline",
    privacyLink: "Privacy policy",
  },
  admin: {
    title: "Admin",
    backToApp: "Back to dashboard",
    nav: { overview: "Overview", users: "Users", jobs: "Jobs", billing: "Billing", audit: "Audit log", media: "Media library", content: "Content review", posts: "Posts" },
    overview: {
      newUsers: "New users",
      proUsers: "Pro users",
      totalUsers: "Total users",
      views: "Page views",
      visitors: "Visitors (consented)",
      topPages: "Top pages",
      topReferrers: "Referrers",
      events: "Events",
      storage: "Storage",
      noData: "No data yet.",
      last30Days: "Last 30 days",
    },
    users: {
      search: "Search by email",
      email: "Email",
      role: "Role",
      status: "Status",
      createdAt: "Created",
      plan: "Plan",
      activeUntil: "Active until",
      orders: "Orders",
      subscriptions: "Subscriptions",
      files: "Files",
      disable: "Disable account",
      enable: "Enable account",
      makeAdmin: "Make admin",
      makeUser: "Remove admin",
      previous: "Previous",
      next: "Next",
      selfNote: "You cannot disable or demote yourself.",
      confirmDisable: "The user will be signed out and cannot sign in again until re-enabled.",
      confirmRole: "This changes the user's access to the admin area.",
      changeRole: "Change role",
      roles: { user: "User", editor: "Editor (content only)", admin: "Admin" },
    },
    jobs: { title: "Failed jobs", name: "Name", attempts: "Attempts", lastError: "Last error", retry: "Retry", empty: "No failed jobs." },
    billing: {
      subscriptions: "Recent subscriptions",
      orders: "Recent VNPay orders",
      problemEvents: "Failed webhooks",
      retry: "Reprocess",
      empty: "None.",
    },
    audit: { title: "Audit log", time: "Time", actor: "Actor", action: "Action", target: "Target", empty: "No admin actions yet." },
    media: {
      title: "Media library",
      upload: "Upload images",
      uploading: "Uploading…",
      search: "Search by file name",
      empty: "No images yet.",
      edit: "Edit image",
      back: "← Media library",
      alt: "Image description (alt)",
      altHint: "Short description of the image for screen readers and Google, e.g. \"Cruise on Ha Long Bay at sunset\".",
      focal: "Focal point",
      focalHint: "Click the main subject: whatever the crop, this point stays in the picture.",
      save: "Save",
      remove: "Delete image",
      removeAsk: "Permanently delete this image from the library?",
      size: "Size",
      errors: {
        format: "Only JPG, PNG, WebP or AVIF images.",
        size: "Image too large.",
        failed: "Upload failed. Please try again.",
        inUse: "This image is used by published content and cannot be deleted.",
      },
    },
    content: {
      title: "Content review",
      description: "Content awaiting review, scheduled and recently edited.",
      empty: "No content.",
      all: "All",
      type: "Type",
      slug: "Slug",
      status: "Status",
      updated: "Updated",
      statuses: { draft: "Draft", pending: "Awaiting review", approved: "Approved, scheduled", published: "Published" },
      hidden: "Hidden",
      live: "Live on the site",
      notLive: "Not on the site yet",
      scheduledFor: "Publishes at",
      reviewNote: "Reviewer's note",
      workflow: "Review workflow",
      submit: "Submit for review",
      publishNow: "Approve and publish now",
      schedule: "Approve and schedule",
      scheduleAt: "Publish at",
      reject: "Send back for changes",
      rejectNote: "What needs changing?",
      hide: "Hide from the site",
      show: "Show on the site again",
      preview: "Preview",
      previewing: "Previewing the draft (visitors do not see it).",
      exitPreview: "Exit preview",
      history: "Version history",
      restore: "Restore",
      restoreAsk: "Copy this version into the draft? The current draft will be replaced.",
      events: { submitted: "Submitted", published: "Published" },
      conflict: "Someone else just changed this content. Reload the page to see the latest version.",
      incomplete: "This content is not complete enough to submit or publish. Fill in the missing parts and try again.",
    },
    posts: {
      title: "Posts",
      description: "Write, submit and publish blog posts. Visitors only see published posts.",
      newPost: "New post",
      edit: "Edit post",
      back: "← Posts",
      empty: "No posts yet.",
      columns: { post: "Post", locale: "Language", status: "Status", live: "On the site", updated: "Updated" },
      yes: "Yes",
      no: "Not yet",
      hidden: "Hidden",
      fields: {
        locale: "Language",
        title: "Title",
        slug: "URL (slug)",
        slugHint: "Lowercase, no accents, words joined by dashes, e.g. ha-long-travel-tips. Changing it after publishing redirects the old link.",
        description: "Short description (post lists and Google)",
        date: "Published on",
        updated: "Updated on (optional)",
        tags: "Tags",
        tagsHint: "Comma separated, lowercase without accents, e.g. ha-long, tips.",
        cover: "Cover image (optional)",
        coverHint: "A path on the site, e.g. /blog/cover.jpg.",
        author: "Author (optional)",
        translationKey: "Translation key (optional)",
        translationKeyHint: "The same key on a Vietnamese and an English post marks them as translations.",
        body: "Content (Markdown)",
        bodyHint: "## Section title, **bold**, - bullet points, [text](link), <Callout>note</Callout>.",
      },
      locales: { vi: "Tiếng Việt", en: "English" },
      save: "Save draft",
      create: "Create draft",
      saving: "Saving…",
      problemsTitle: "Missing before you can submit:",
      result: {
        saved: "Draft saved.",
        created: "Draft created. Write the content, then submit for review.",
        slug_taken: "Another post already uses this URL.",
        invalid: "Invalid data. Please check the fields.",
      },
    },
    done: "Done.",
    failed: "Could not complete the action.",
    confirmTitle: "Confirm action",
    cancel: "Cancel",
  },
  blog: {
    nav: "Blog",
    title: "Blog",
    subtitle: "News, tips and guides.",
    readingTime: "{n} min read",
    tagTitle: "Posts about",
    tags: "Topics",
    empty: "No posts yet.",
    previous: "Previous page",
    next: "Next page",
    allPosts: "All posts",
    updated: "Updated",
    otherLanguage: "Đọc bằng tiếng Việt",
    rss: "RSS",
  },
};
