import type { Locale } from "@/config/app";

const vi = {
  title: "Tour",
  description: "Soạn, gửi duyệt và công khai tour. Khách chỉ thấy bản đã công khai.",
  newTour: "Tạo tour mới",
  duplicate: "Nhân bản",
  edit: "Sửa",
  back: "← Danh sách tour",
  empty: "Chưa có tour nào.",
  search: "Tìm theo tên hoặc đường dẫn",
  searchButton: "Tìm",
  noMatch: "Không có tour nào khớp.",
  showAll: "Xem tất cả",
  columns: { tour: "Tour", status: "Trạng thái", live: "Trên web", missing: "Còn thiếu", updated: "Cập nhật" },
  yes: "Có",
  no: "Chưa",
  hidden: "Đang ẩn",
  complete: "Đủ",
  missingCount: (n: number) => `${n} mục`,
  create: {
    title: "Tạo tour mới",
    slug: "Đường dẫn (slug)",
    slugHint: "Chữ thường không dấu, nối bằng gạch ngang, ví dụ: ha-long-3-ngay-2-dem.",
    titleVi: "Tên tour (tiếng Việt)",
    submit: "Tạo bản nháp",
  },
  tabs: { general: "Chung", vi: "Tiếng Việt", en: "English", seo: "SEO", images: "Ảnh", private: "Tour riêng", addons: "Dịch vụ thêm" },
  activityLevels: { "": "Không ghi", easy: "Nhẹ nhàng", moderate: "Vừa phải", challenging: "Khá vất vả" },
  fields: {
    destination: "Điểm đến",
    days: "Số ngày",
    nights: "Số đêm",
    priceVnd: "Giá người lớn (VND)",
    priceUsd: "Giá người lớn (USD)",
    addonsHint: "Khách chọn thêm khi đặt tour (đón tại khách sạn, ăn chay, thuê xe máy…). Giá cộng vào tổng tiền.",
    addonNameVi: "Tên (tiếng Việt)",
    addonNameEn: "Tên (English)",
    addonVnd: "Giá (VND)",
    addonPer: "Tính theo",
    addonPerPerson: "Mỗi khách",
    addonPerBooking: "Mỗi đơn",
    addons: "Dịch vụ thêm",
    activity: "Mức vận động",
    pickupTime: "Giờ đón (ví dụ: 7:30–8:00 tại khách sạn phố cổ)",
    bring: "Cần mang theo",
    childPercent: "Giá trẻ em (% giá người lớn, mặc định 75)",
    infantVnd: "Giá em bé (VND, mặc định 0 = miễn phí)",
    singleSupplementVnd: "Phụ thu phòng đơn (VND/phòng, 0 = không áp dụng; chỉ tour có đêm)",
    pricing: "Giá theo đối tượng",
    featured: "Hiện ở mục \"Tour được đặt nhiều\" trên trang chủ",
    order: "Thứ tự trong điểm đến (nhỏ đứng trước)",
    title: "Tên tour",
    summary: "Mô tả ngắn (hiện trên thẻ tour và Google)",
    departure: "Khởi hành / đón khách",
    groupSize: "Quy mô đoàn",
    highlights: "Điểm nổi bật",
    itinerary: "Lịch trình",
    dayTitle: "Tiêu đề ngày",
    dayDescription: "Hoạt động trong ngày",
    includes: "Giá bao gồm",
    excludes: "Giá không bao gồm",
    body: "Giới thiệu (Markdown)",
    bodyHint: "**chữ đậm**, - gạch đầu dòng, <Callout>ghi chú</Callout>.",
    images: "Ảnh tour (ảnh đầu tiên là ảnh bìa)",
    addImage: "Thêm ảnh",
    privateOn: "Có nhận tour riêng (xe, hướng dẫn viên, ngày riêng)",
    maxGuests: "Số khách tối đa",
    tiers: "Giá theo số khách (mỗi người)",
    minGuests: "Từ số khách",
    seoTitle: "Tiêu đề trên Google",
    seoDescription: "Mô tả trên Google",
  },
  seo: {
    intro: "Không bắt buộc. Để trống thì Google dùng tên tour và mô tả ngắn.",
    titleHint: "Nên dưới 60 ký tự, có tên điểm đến và số ngày.",
    descriptionHint: "Nên 120–155 ký tự: điểm hấp dẫn nhất và giá hoặc lợi ích chính.",
    chars: (n: number, max: number) => `${n}/${max} ký tự`,
    previewTitle: "Hiển thị trên Google (ước lượng)",
  },
  add: "Thêm",
  remove: "Xoá",
  up: "Lên",
  down: "Xuống",
  save: "Lưu bản nháp",
  saving: "Đang lưu…",
  unsaved: "Có thay đổi chưa lưu. Rời trang và bỏ các thay đổi này?",
  slugLocked: "Đã công khai. Nếu đổi đường dẫn, link cũ sẽ tự chuyển sang link mới khi bản này được công khai.",
  problemsTitle: "Còn thiếu trước khi gửi duyệt:",
  previewNoBooking: "Đang xem trước: đặt tour và hỏi tour bị tắt trên bản nháp.",
  problemLabels: {
    shared: "Chung",
    vi: "Tiếng Việt",
    en: "English",
  } as Record<string, string>,
  result: {
    saved: "Đã lưu bản nháp.",
    created: "Đã tạo bản nháp. Điền các tab rồi gửi duyệt.",
    duplicated: "Đã nhân bản. Đổi tên và đường dẫn rồi gửi duyệt.",
    slug_taken: "Đường dẫn này đã có tour khác dùng.",
    invalid: "Dữ liệu không hợp lệ. Kiểm tra lại các ô.",
  },
};

type TourAdminContent = typeof vi;

const en: TourAdminContent = {
  title: "Tours",
  description: "Write, submit and publish tours. Visitors only see published versions.",
  newTour: "New tour",
  duplicate: "Duplicate",
  edit: "Edit",
  back: "← Tours",
  empty: "No tours yet.",
  search: "Search by name or URL",
  searchButton: "Search",
  noMatch: "No tours match.",
  showAll: "Show all",
  columns: { tour: "Tour", status: "Status", live: "On the site", missing: "Missing", updated: "Updated" },
  yes: "Yes",
  no: "Not yet",
  hidden: "Hidden",
  complete: "Complete",
  missingCount: (n: number) => `${n} field${n === 1 ? "" : "s"}`,
  create: {
    title: "New tour",
    slug: "URL (slug)",
    slugHint: "Lowercase, no accents, words joined by dashes, e.g. ha-long-3-days-2-nights.",
    titleVi: "Tour name (Vietnamese)",
    submit: "Create draft",
  },
  tabs: { general: "General", vi: "Tiếng Việt", en: "English", seo: "SEO", images: "Images", private: "Private tour", addons: "Add-ons" },
  activityLevels: { "": "Not shown", easy: "Easy", moderate: "Moderate", challenging: "Challenging" },
  fields: {
    destination: "Destination",
    days: "Days",
    nights: "Nights",
    priceVnd: "Adult price (VND)",
    priceUsd: "Adult price (USD)",
    addonsHint: "Extras guests can add when booking (hotel pick-up, vegetarian meals, motorbike…). Added to the total.",
    addonNameVi: "Name (Vietnamese)",
    addonNameEn: "Name (English)",
    addonVnd: "Price (VND)",
    addonPer: "Charged",
    addonPerPerson: "Per traveller",
    addonPerBooking: "Per booking",
    addons: "Add-ons",
    activity: "Activity level",
    pickupTime: "Pick-up time (e.g. 7:30–8:00 at Old Quarter hotels)",
    bring: "What to bring",
    childPercent: "Child price (% of adult, default 75)",
    infantVnd: "Infant price (VND, default 0 = free)",
    singleSupplementVnd: "Single room supplement (VND per room, 0 = none; tours with nights only)",
    pricing: "Prices by traveller",
    featured: "Show in \"Popular tours\" on the home page",
    order: "Order within the destination (lower first)",
    title: "Tour name",
    summary: "Short description (tour cards and Google)",
    departure: "Departure / pickup",
    groupSize: "Group size",
    highlights: "Highlights",
    itinerary: "Itinerary",
    dayTitle: "Day title",
    dayDescription: "Activities of the day",
    includes: "Included",
    excludes: "Not included",
    body: "Overview (Markdown)",
    bodyHint: "**bold**, - bullet points, <Callout>note</Callout>.",
    images: "Tour images (the first one is the cover)",
    addImage: "Add image",
    privateOn: "Offer private tours (own vehicle, guide and date)",
    maxGuests: "Maximum guests",
    tiers: "Price by group size (per guest)",
    minGuests: "From guests",
    seoTitle: "Google title",
    seoDescription: "Google description",
  },
  seo: {
    intro: "Optional. When empty, Google shows the tour name and short description.",
    titleHint: "Keep it under 60 characters, with the destination and the number of days.",
    descriptionHint: "Aim for 120–155 characters: the main draw and the price or key benefit.",
    chars: (n: number, max: number) => `${n}/${max} characters`,
    previewTitle: "On Google (approximate)",
  },
  add: "Add",
  remove: "Remove",
  up: "Up",
  down: "Down",
  save: "Save draft",
  saving: "Saving…",
  unsaved: "You have unsaved changes. Leave the page and discard them?",
  slugLocked: "Published. If you change the URL, the old link redirects to the new one once this version is published.",
  problemsTitle: "Missing before you can submit:",
  previewNoBooking: "Previewing: booking and inquiries are off on a draft.",
  problemLabels: { shared: "General", vi: "Tiếng Việt", en: "English" },
  result: {
    saved: "Draft saved.",
    created: "Draft created. Fill in the tabs, then submit for review.",
    duplicated: "Duplicated. Change the name and URL, then submit for review.",
    slug_taken: "Another tour already uses this URL.",
    invalid: "Invalid data. Please check the fields.",
  },
};

/** "en.itinerary.0.title" → "English › Lịch trình #1": the words of the form labels, not field names. */
export function tourProblemLabel(path: string, c: TourAdminContent): string {
  const labels: Record<string, string> = { ...c.fields, price: c.fields.priceVnd, private: c.tabs.private };
  const [section, key, index] = path.split(".");
  const field = key ? (labels[key] ?? key) : "—";
  const detail = index === undefined ? "" : /^\d+$/.test(index) ? ` #${Number(index) + 1}` : labels[index] ? ` › ${labels[index]}` : "";
  return `${c.problemLabels[section!] ?? section} › ${field}${detail}`;
}

export function getTourAdminContent(locale: Locale): TourAdminContent {
  return locale === "en" ? en : vi;
}
export type { TourAdminContent };
