import type { Locale } from "@/config/app";

const vi = {
  title: "Tour",
  description: "Soạn, gửi duyệt và công khai tour. Khách chỉ thấy bản đã công khai.",
  newTour: "Tạo tour mới",
  duplicate: "Nhân bản",
  edit: "Sửa",
  back: "← Danh sách tour",
  empty: "Chưa có tour nào.",
  columns: { tour: "Tour", status: "Trạng thái", live: "Trên web", missing: "Còn thiếu", updated: "Cập nhật" },
  yes: "Có",
  no: "Chưa",
  hidden: "Đang ẩn",
  complete: "Đủ",
  missingCount: (n: number) => `${n} mục`,
  create: {
    title: "Tạo tour mới",
    slug: "Đường dẫn (slug)",
    slugHint: "Chữ thường không dấu, nối bằng gạch ngang, ví dụ: ha-long-3-ngay-2-dem. Không đổi được sau khi công khai.",
    titleVi: "Tên tour (tiếng Việt)",
    submit: "Tạo bản nháp",
  },
  tabs: { general: "Chung", vi: "Tiếng Việt", en: "English", images: "Ảnh", private: "Tour riêng" },
  fields: {
    destination: "Điểm đến",
    days: "Số ngày",
    nights: "Số đêm",
    priceVnd: "Giá người lớn (VND)",
    priceUsd: "Giá người lớn (USD)",
    featured: "Hiện ở mục \"Tour được đặt nhiều\" trên trang chủ",
    order: "Thứ tự trong điểm đến (nhỏ đứng trước)",
    title: "Tên tour",
    summary: "Mô tả ngắn (hiện trên thẻ tour và Google)",
    departure: "Khởi hành / đón khách",
    groupSize: "Quy mô đoàn",
    highlights: "Điểm nổi bật",
    itinerary: "Lịch trình",
    dayTitle: "Tiêu đề ngày",
    dayDescription: "Hoạt động trong ngày",
    includes: "Giá bao gồm",
    excludes: "Giá không bao gồm",
    body: "Giới thiệu (Markdown)",
    bodyHint: "**chữ đậm**, - gạch đầu dòng, <Callout>ghi chú</Callout>.",
    images: "Ảnh tour (ảnh đầu tiên là ảnh bìa)",
    addImage: "Thêm ảnh",
    privateOn: "Có nhận tour riêng (xe, hướng dẫn viên, ngày riêng)",
    maxGuests: "Số khách tối đa",
    tiers: "Giá theo số khách (mỗi người)",
    minGuests: "Từ số khách",
  },
  add: "Thêm",
  remove: "Xoá",
  up: "Lên",
  down: "Xuống",
  save: "Lưu bản nháp",
  saving: "Đang lưu…",
  slugLocked: "Đã công khai: đường dẫn bị khoá để link cũ không hỏng.",
  problemsTitle: "Còn thiếu trước khi gửi duyệt:",
  problemLabels: {
    shared: "Chung",
    vi: "Tiếng Việt",
    en: "English",
  } as Record<string, string>,
  result: {
    saved: "Đã lưu bản nháp.",
    created: "Đã tạo bản nháp. Điền các tab rồi gửi duyệt.",
    duplicated: "Đã nhân bản. Đổi tên và đường dẫn rồi gửi duyệt.",
    slug_taken: "Đường dẫn này đã có tour khác dùng.",
    invalid: "Dữ liệu không hợp lệ. Kiểm tra lại các ô.",
  },
};

type TourAdminContent = typeof vi;

const en: TourAdminContent = {
  title: "Tours",
  description: "Write, submit and publish tours. Visitors only see published versions.",
  newTour: "New tour",
  duplicate: "Duplicate",
  edit: "Edit",
  back: "← Tours",
  empty: "No tours yet.",
  columns: { tour: "Tour", status: "Status", live: "On the site", missing: "Missing", updated: "Updated" },
  yes: "Yes",
  no: "Not yet",
  hidden: "Hidden",
  complete: "Complete",
  missingCount: (n: number) => `${n} field${n === 1 ? "" : "s"}`,
  create: {
    title: "New tour",
    slug: "URL (slug)",
    slugHint: "Lowercase, no accents, words joined by dashes, e.g. ha-long-3-days-2-nights. Locked once published.",
    titleVi: "Tour name (Vietnamese)",
    submit: "Create draft",
  },
  tabs: { general: "General", vi: "Tiếng Việt", en: "English", images: "Images", private: "Private tour" },
  fields: {
    destination: "Destination",
    days: "Days",
    nights: "Nights",
    priceVnd: "Adult price (VND)",
    priceUsd: "Adult price (USD)",
    featured: "Show in \"Popular tours\" on the home page",
    order: "Order within the destination (lower first)",
    title: "Tour name",
    summary: "Short description (tour cards and Google)",
    departure: "Departure / pickup",
    groupSize: "Group size",
    highlights: "Highlights",
    itinerary: "Itinerary",
    dayTitle: "Day title",
    dayDescription: "Activities of the day",
    includes: "Included",
    excludes: "Not included",
    body: "Overview (Markdown)",
    bodyHint: "**bold**, - bullet points, <Callout>note</Callout>.",
    images: "Tour images (the first one is the cover)",
    addImage: "Add image",
    privateOn: "Offer private tours (own vehicle, guide and date)",
    maxGuests: "Maximum guests",
    tiers: "Price by group size (per guest)",
    minGuests: "From guests",
  },
  add: "Add",
  remove: "Remove",
  up: "Up",
  down: "Down",
  save: "Save draft",
  saving: "Saving…",
  slugLocked: "Published: the URL is locked so existing links keep working.",
  problemsTitle: "Missing before you can submit:",
  problemLabels: { shared: "General", vi: "Tiếng Việt", en: "English" },
  result: {
    saved: "Draft saved.",
    created: "Draft created. Fill in the tabs, then submit for review.",
    duplicated: "Duplicated. Change the name and URL, then submit for review.",
    slug_taken: "Another tour already uses this URL.",
    invalid: "Invalid data. Please check the fields.",
  },
};

export function getTourAdminContent(locale: Locale): TourAdminContent {
  return locale === "en" ? en : vi;
}
export type { TourAdminContent };
